package com.wildwolf.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DrugstoreExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DRUGSTORE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DRUGSTORE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DRUGSTORE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DRUGSTORE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public DrugstoreExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DRUGSTORE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    protected DrugstoreExample(DrugstoreExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.distinct = example.distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DRUGSTORE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DRUGSTORE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DRUGSTORE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DRUGSTORE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DRUGSTORE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DRUGSTORE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DRUGSTORE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DRUGSTORE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DRUGSTORE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DRUGSTORE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DRUGSTORE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected GeneratedCriteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andDRUGSTOREIDIsNull() {
            addCriterion("DRUGSTOREID is null");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDIsNotNull() {
            addCriterion("DRUGSTOREID is not null");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDEqualTo(String value) {
            addCriterion("DRUGSTOREID =", value, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDNotEqualTo(String value) {
            addCriterion("DRUGSTOREID <>", value, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDGreaterThan(String value) {
            addCriterion("DRUGSTOREID >", value, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDGreaterThanOrEqualTo(String value) {
            addCriterion("DRUGSTOREID >=", value, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDLessThan(String value) {
            addCriterion("DRUGSTOREID <", value, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDLessThanOrEqualTo(String value) {
            addCriterion("DRUGSTOREID <=", value, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDLike(String value) {
            addCriterion("DRUGSTOREID like", value, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDNotLike(String value) {
            addCriterion("DRUGSTOREID not like", value, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDIn(List values) {
            addCriterion("DRUGSTOREID in", values, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDNotIn(List values) {
            addCriterion("DRUGSTOREID not in", values, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDBetween(String value1, String value2) {
            addCriterion("DRUGSTOREID between", value1, value2, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDNotBetween(String value1, String value2) {
            addCriterion("DRUGSTOREID not between", value1, value2, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andBUSINESSOPERATIONIDIsNull() {
            addCriterion("BUSINESSOPERATIONID is null");
            return (Criteria) this;
        }

        public Criteria andBUSINESSOPERATIONIDIsNotNull() {
            addCriterion("BUSINESSOPERATIONID is not null");
            return (Criteria) this;
        }

        public Criteria andBUSINESSOPERATIONIDEqualTo(String value) {
            addCriterion("BUSINESSOPERATIONID =", value, "BUSINESSOPERATIONID");
            return (Criteria) this;
        }

        public Criteria andBUSINESSOPERATIONIDNotEqualTo(String value) {
            addCriterion("BUSINESSOPERATIONID <>", value, "BUSINESSOPERATIONID");
            return (Criteria) this;
        }

        public Criteria andBUSINESSOPERATIONIDGreaterThan(String value) {
            addCriterion("BUSINESSOPERATIONID >", value, "BUSINESSOPERATIONID");
            return (Criteria) this;
        }

        public Criteria andBUSINESSOPERATIONIDGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESSOPERATIONID >=", value, "BUSINESSOPERATIONID");
            return (Criteria) this;
        }

        public Criteria andBUSINESSOPERATIONIDLessThan(String value) {
            addCriterion("BUSINESSOPERATIONID <", value, "BUSINESSOPERATIONID");
            return (Criteria) this;
        }

        public Criteria andBUSINESSOPERATIONIDLessThanOrEqualTo(String value) {
            addCriterion("BUSINESSOPERATIONID <=", value, "BUSINESSOPERATIONID");
            return (Criteria) this;
        }

        public Criteria andBUSINESSOPERATIONIDLike(String value) {
            addCriterion("BUSINESSOPERATIONID like", value, "BUSINESSOPERATIONID");
            return (Criteria) this;
        }

        public Criteria andBUSINESSOPERATIONIDNotLike(String value) {
            addCriterion("BUSINESSOPERATIONID not like", value, "BUSINESSOPERATIONID");
            return (Criteria) this;
        }

        public Criteria andBUSINESSOPERATIONIDIn(List values) {
            addCriterion("BUSINESSOPERATIONID in", values, "BUSINESSOPERATIONID");
            return (Criteria) this;
        }

        public Criteria andBUSINESSOPERATIONIDNotIn(List values) {
            addCriterion("BUSINESSOPERATIONID not in", values, "BUSINESSOPERATIONID");
            return (Criteria) this;
        }

        public Criteria andBUSINESSOPERATIONIDBetween(String value1, String value2) {
            addCriterion("BUSINESSOPERATIONID between", value1, value2, "BUSINESSOPERATIONID");
            return (Criteria) this;
        }

        public Criteria andBUSINESSOPERATIONIDNotBetween(String value1, String value2) {
            addCriterion("BUSINESSOPERATIONID not between", value1, value2, "BUSINESSOPERATIONID");
            return (Criteria) this;
        }

        public Criteria andDSNAMEIsNull() {
            addCriterion("DSNAME is null");
            return (Criteria) this;
        }

        public Criteria andDSNAMEIsNotNull() {
            addCriterion("DSNAME is not null");
            return (Criteria) this;
        }

        public Criteria andDSNAMEEqualTo(String value) {
            addCriterion("DSNAME =", value, "DSNAME");
            return (Criteria) this;
        }

        public Criteria andDSNAMENotEqualTo(String value) {
            addCriterion("DSNAME <>", value, "DSNAME");
            return (Criteria) this;
        }

        public Criteria andDSNAMEGreaterThan(String value) {
            addCriterion("DSNAME >", value, "DSNAME");
            return (Criteria) this;
        }

        public Criteria andDSNAMEGreaterThanOrEqualTo(String value) {
            addCriterion("DSNAME >=", value, "DSNAME");
            return (Criteria) this;
        }

        public Criteria andDSNAMELessThan(String value) {
            addCriterion("DSNAME <", value, "DSNAME");
            return (Criteria) this;
        }

        public Criteria andDSNAMELessThanOrEqualTo(String value) {
            addCriterion("DSNAME <=", value, "DSNAME");
            return (Criteria) this;
        }

        public Criteria andDSNAMELike(String value) {
            addCriterion("DSNAME like", value, "DSNAME");
            return (Criteria) this;
        }

        public Criteria andDSNAMENotLike(String value) {
            addCriterion("DSNAME not like", value, "DSNAME");
            return (Criteria) this;
        }

        public Criteria andDSNAMEIn(List values) {
            addCriterion("DSNAME in", values, "DSNAME");
            return (Criteria) this;
        }

        public Criteria andDSNAMENotIn(List values) {
            addCriterion("DSNAME not in", values, "DSNAME");
            return (Criteria) this;
        }

        public Criteria andDSNAMEBetween(String value1, String value2) {
            addCriterion("DSNAME between", value1, value2, "DSNAME");
            return (Criteria) this;
        }

        public Criteria andDSNAMENotBetween(String value1, String value2) {
            addCriterion("DSNAME not between", value1, value2, "DSNAME");
            return (Criteria) this;
        }

        public Criteria andADDRESSIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andADDRESSIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andADDRESSEqualTo(String value) {
            addCriterion("ADDRESS =", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSLessThan(String value) {
            addCriterion("ADDRESS <", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSLike(String value) {
            addCriterion("ADDRESS like", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSNotLike(String value) {
            addCriterion("ADDRESS not like", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSIn(List values) {
            addCriterion("ADDRESS in", values, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSNotIn(List values) {
            addCriterion("ADDRESS not in", values, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andRESPONSIBLEPERSONIsNull() {
            addCriterion("RESPONSIBLEPERSON is null");
            return (Criteria) this;
        }

        public Criteria andRESPONSIBLEPERSONIsNotNull() {
            addCriterion("RESPONSIBLEPERSON is not null");
            return (Criteria) this;
        }

        public Criteria andRESPONSIBLEPERSONEqualTo(String value) {
            addCriterion("RESPONSIBLEPERSON =", value, "RESPONSIBLEPERSON");
            return (Criteria) this;
        }

        public Criteria andRESPONSIBLEPERSONNotEqualTo(String value) {
            addCriterion("RESPONSIBLEPERSON <>", value, "RESPONSIBLEPERSON");
            return (Criteria) this;
        }

        public Criteria andRESPONSIBLEPERSONGreaterThan(String value) {
            addCriterion("RESPONSIBLEPERSON >", value, "RESPONSIBLEPERSON");
            return (Criteria) this;
        }

        public Criteria andRESPONSIBLEPERSONGreaterThanOrEqualTo(String value) {
            addCriterion("RESPONSIBLEPERSON >=", value, "RESPONSIBLEPERSON");
            return (Criteria) this;
        }

        public Criteria andRESPONSIBLEPERSONLessThan(String value) {
            addCriterion("RESPONSIBLEPERSON <", value, "RESPONSIBLEPERSON");
            return (Criteria) this;
        }

        public Criteria andRESPONSIBLEPERSONLessThanOrEqualTo(String value) {
            addCriterion("RESPONSIBLEPERSON <=", value, "RESPONSIBLEPERSON");
            return (Criteria) this;
        }

        public Criteria andRESPONSIBLEPERSONLike(String value) {
            addCriterion("RESPONSIBLEPERSON like", value, "RESPONSIBLEPERSON");
            return (Criteria) this;
        }

        public Criteria andRESPONSIBLEPERSONNotLike(String value) {
            addCriterion("RESPONSIBLEPERSON not like", value, "RESPONSIBLEPERSON");
            return (Criteria) this;
        }

        public Criteria andRESPONSIBLEPERSONIn(List values) {
            addCriterion("RESPONSIBLEPERSON in", values, "RESPONSIBLEPERSON");
            return (Criteria) this;
        }

        public Criteria andRESPONSIBLEPERSONNotIn(List values) {
            addCriterion("RESPONSIBLEPERSON not in", values, "RESPONSIBLEPERSON");
            return (Criteria) this;
        }

        public Criteria andRESPONSIBLEPERSONBetween(String value1, String value2) {
            addCriterion("RESPONSIBLEPERSON between", value1, value2, "RESPONSIBLEPERSON");
            return (Criteria) this;
        }

        public Criteria andRESPONSIBLEPERSONNotBetween(String value1, String value2) {
            addCriterion("RESPONSIBLEPERSON not between", value1, value2, "RESPONSIBLEPERSON");
            return (Criteria) this;
        }

        public Criteria andCREATEDATEIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCREATEDATEIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCREATEDATEEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATENotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATEGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATEGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATELessThan(Date value) {
            addCriterion("CREATEDATE <", value, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATELessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATEIn(List values) {
            addCriterion("CREATEDATE in", values, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATENotIn(List values) {
            addCriterion("CREATEDATE not in", values, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATEBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATENotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEBYIsNull() {
            addCriterion("CREATEBY is null");
            return (Criteria) this;
        }

        public Criteria andCREATEBYIsNotNull() {
            addCriterion("CREATEBY is not null");
            return (Criteria) this;
        }

        public Criteria andCREATEBYEqualTo(String value) {
            addCriterion("CREATEBY =", value, "CREATEBY");
            return (Criteria) this;
        }

        public Criteria andCREATEBYNotEqualTo(String value) {
            addCriterion("CREATEBY <>", value, "CREATEBY");
            return (Criteria) this;
        }

        public Criteria andCREATEBYGreaterThan(String value) {
            addCriterion("CREATEBY >", value, "CREATEBY");
            return (Criteria) this;
        }

        public Criteria andCREATEBYGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEBY >=", value, "CREATEBY");
            return (Criteria) this;
        }

        public Criteria andCREATEBYLessThan(String value) {
            addCriterion("CREATEBY <", value, "CREATEBY");
            return (Criteria) this;
        }

        public Criteria andCREATEBYLessThanOrEqualTo(String value) {
            addCriterion("CREATEBY <=", value, "CREATEBY");
            return (Criteria) this;
        }

        public Criteria andCREATEBYLike(String value) {
            addCriterion("CREATEBY like", value, "CREATEBY");
            return (Criteria) this;
        }

        public Criteria andCREATEBYNotLike(String value) {
            addCriterion("CREATEBY not like", value, "CREATEBY");
            return (Criteria) this;
        }

        public Criteria andCREATEBYIn(List values) {
            addCriterion("CREATEBY in", values, "CREATEBY");
            return (Criteria) this;
        }

        public Criteria andCREATEBYNotIn(List values) {
            addCriterion("CREATEBY not in", values, "CREATEBY");
            return (Criteria) this;
        }

        public Criteria andCREATEBYBetween(String value1, String value2) {
            addCriterion("CREATEBY between", value1, value2, "CREATEBY");
            return (Criteria) this;
        }

        public Criteria andCREATEBYNotBetween(String value1, String value2) {
            addCriterion("CREATEBY not between", value1, value2, "CREATEBY");
            return (Criteria) this;
        }

        public Criteria andTELIsNull() {
            addCriterion("TEL is null");
            return (Criteria) this;
        }

        public Criteria andTELIsNotNull() {
            addCriterion("TEL is not null");
            return (Criteria) this;
        }

        public Criteria andTELEqualTo(String value) {
            addCriterion("TEL =", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELNotEqualTo(String value) {
            addCriterion("TEL <>", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELGreaterThan(String value) {
            addCriterion("TEL >", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELGreaterThanOrEqualTo(String value) {
            addCriterion("TEL >=", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELLessThan(String value) {
            addCriterion("TEL <", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELLessThanOrEqualTo(String value) {
            addCriterion("TEL <=", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELLike(String value) {
            addCriterion("TEL like", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELNotLike(String value) {
            addCriterion("TEL not like", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELIn(List values) {
            addCriterion("TEL in", values, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELNotIn(List values) {
            addCriterion("TEL not in", values, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELBetween(String value1, String value2) {
            addCriterion("TEL between", value1, value2, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELNotBetween(String value1, String value2) {
            addCriterion("TEL not between", value1, value2, "TEL");
            return (Criteria) this;
        }

        public Criteria andREGIONIsNull() {
            addCriterion("REGION is null");
            return (Criteria) this;
        }

        public Criteria andREGIONIsNotNull() {
            addCriterion("REGION is not null");
            return (Criteria) this;
        }

        public Criteria andREGIONEqualTo(String value) {
            addCriterion("REGION =", value, "REGION");
            return (Criteria) this;
        }

        public Criteria andREGIONNotEqualTo(String value) {
            addCriterion("REGION <>", value, "REGION");
            return (Criteria) this;
        }

        public Criteria andREGIONGreaterThan(String value) {
            addCriterion("REGION >", value, "REGION");
            return (Criteria) this;
        }

        public Criteria andREGIONGreaterThanOrEqualTo(String value) {
            addCriterion("REGION >=", value, "REGION");
            return (Criteria) this;
        }

        public Criteria andREGIONLessThan(String value) {
            addCriterion("REGION <", value, "REGION");
            return (Criteria) this;
        }

        public Criteria andREGIONLessThanOrEqualTo(String value) {
            addCriterion("REGION <=", value, "REGION");
            return (Criteria) this;
        }

        public Criteria andREGIONLike(String value) {
            addCriterion("REGION like", value, "REGION");
            return (Criteria) this;
        }

        public Criteria andREGIONNotLike(String value) {
            addCriterion("REGION not like", value, "REGION");
            return (Criteria) this;
        }

        public Criteria andREGIONIn(List values) {
            addCriterion("REGION in", values, "REGION");
            return (Criteria) this;
        }

        public Criteria andREGIONNotIn(List values) {
            addCriterion("REGION not in", values, "REGION");
            return (Criteria) this;
        }

        public Criteria andREGIONBetween(String value1, String value2) {
            addCriterion("REGION between", value1, value2, "REGION");
            return (Criteria) this;
        }

        public Criteria andREGIONNotBetween(String value1, String value2) {
            addCriterion("REGION not between", value1, value2, "REGION");
            return (Criteria) this;
        }

        public Criteria andBUSINESSMODELIsNull() {
            addCriterion("BUSINESSMODEL is null");
            return (Criteria) this;
        }

        public Criteria andBUSINESSMODELIsNotNull() {
            addCriterion("BUSINESSMODEL is not null");
            return (Criteria) this;
        }

        public Criteria andBUSINESSMODELEqualTo(String value) {
            addCriterion("BUSINESSMODEL =", value, "BUSINESSMODEL");
            return (Criteria) this;
        }

        public Criteria andBUSINESSMODELNotEqualTo(String value) {
            addCriterion("BUSINESSMODEL <>", value, "BUSINESSMODEL");
            return (Criteria) this;
        }

        public Criteria andBUSINESSMODELGreaterThan(String value) {
            addCriterion("BUSINESSMODEL >", value, "BUSINESSMODEL");
            return (Criteria) this;
        }

        public Criteria andBUSINESSMODELGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESSMODEL >=", value, "BUSINESSMODEL");
            return (Criteria) this;
        }

        public Criteria andBUSINESSMODELLessThan(String value) {
            addCriterion("BUSINESSMODEL <", value, "BUSINESSMODEL");
            return (Criteria) this;
        }

        public Criteria andBUSINESSMODELLessThanOrEqualTo(String value) {
            addCriterion("BUSINESSMODEL <=", value, "BUSINESSMODEL");
            return (Criteria) this;
        }

        public Criteria andBUSINESSMODELLike(String value) {
            addCriterion("BUSINESSMODEL like", value, "BUSINESSMODEL");
            return (Criteria) this;
        }

        public Criteria andBUSINESSMODELNotLike(String value) {
            addCriterion("BUSINESSMODEL not like", value, "BUSINESSMODEL");
            return (Criteria) this;
        }

        public Criteria andBUSINESSMODELIn(List values) {
            addCriterion("BUSINESSMODEL in", values, "BUSINESSMODEL");
            return (Criteria) this;
        }

        public Criteria andBUSINESSMODELNotIn(List values) {
            addCriterion("BUSINESSMODEL not in", values, "BUSINESSMODEL");
            return (Criteria) this;
        }

        public Criteria andBUSINESSMODELBetween(String value1, String value2) {
            addCriterion("BUSINESSMODEL between", value1, value2, "BUSINESSMODEL");
            return (Criteria) this;
        }

        public Criteria andBUSINESSMODELNotBetween(String value1, String value2) {
            addCriterion("BUSINESSMODEL not between", value1, value2, "BUSINESSMODEL");
            return (Criteria) this;
        }

        public Criteria andBUSINESSSCOPEIsNull() {
            addCriterion("BUSINESSSCOPE is null");
            return (Criteria) this;
        }

        public Criteria andBUSINESSSCOPEIsNotNull() {
            addCriterion("BUSINESSSCOPE is not null");
            return (Criteria) this;
        }

        public Criteria andBUSINESSSCOPEEqualTo(String value) {
            addCriterion("BUSINESSSCOPE =", value, "BUSINESSSCOPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESSSCOPENotEqualTo(String value) {
            addCriterion("BUSINESSSCOPE <>", value, "BUSINESSSCOPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESSSCOPEGreaterThan(String value) {
            addCriterion("BUSINESSSCOPE >", value, "BUSINESSSCOPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESSSCOPEGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESSSCOPE >=", value, "BUSINESSSCOPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESSSCOPELessThan(String value) {
            addCriterion("BUSINESSSCOPE <", value, "BUSINESSSCOPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESSSCOPELessThanOrEqualTo(String value) {
            addCriterion("BUSINESSSCOPE <=", value, "BUSINESSSCOPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESSSCOPELike(String value) {
            addCriterion("BUSINESSSCOPE like", value, "BUSINESSSCOPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESSSCOPENotLike(String value) {
            addCriterion("BUSINESSSCOPE not like", value, "BUSINESSSCOPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESSSCOPEIn(List values) {
            addCriterion("BUSINESSSCOPE in", values, "BUSINESSSCOPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESSSCOPENotIn(List values) {
            addCriterion("BUSINESSSCOPE not in", values, "BUSINESSSCOPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESSSCOPEBetween(String value1, String value2) {
            addCriterion("BUSINESSSCOPE between", value1, value2, "BUSINESSSCOPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESSSCOPENotBetween(String value1, String value2) {
            addCriterion("BUSINESSSCOPE not between", value1, value2, "BUSINESSSCOPE");
            return (Criteria) this;
        }

        public Criteria andFAXIsNull() {
            addCriterion("FAX is null");
            return (Criteria) this;
        }

        public Criteria andFAXIsNotNull() {
            addCriterion("FAX is not null");
            return (Criteria) this;
        }

        public Criteria andFAXEqualTo(String value) {
            addCriterion("FAX =", value, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXNotEqualTo(String value) {
            addCriterion("FAX <>", value, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXGreaterThan(String value) {
            addCriterion("FAX >", value, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXGreaterThanOrEqualTo(String value) {
            addCriterion("FAX >=", value, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXLessThan(String value) {
            addCriterion("FAX <", value, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXLessThanOrEqualTo(String value) {
            addCriterion("FAX <=", value, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXLike(String value) {
            addCriterion("FAX like", value, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXNotLike(String value) {
            addCriterion("FAX not like", value, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXIn(List values) {
            addCriterion("FAX in", values, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXNotIn(List values) {
            addCriterion("FAX not in", values, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXBetween(String value1, String value2) {
            addCriterion("FAX between", value1, value2, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXNotBetween(String value1, String value2) {
            addCriterion("FAX not between", value1, value2, "FAX");
            return (Criteria) this;
        }

        public Criteria andVIDEOURLIsNull() {
            addCriterion("VIDEOURL is null");
            return (Criteria) this;
        }

        public Criteria andVIDEOURLIsNotNull() {
            addCriterion("VIDEOURL is not null");
            return (Criteria) this;
        }

        public Criteria andVIDEOURLEqualTo(String value) {
            addCriterion("VIDEOURL =", value, "VIDEOURL");
            return (Criteria) this;
        }

        public Criteria andVIDEOURLNotEqualTo(String value) {
            addCriterion("VIDEOURL <>", value, "VIDEOURL");
            return (Criteria) this;
        }

        public Criteria andVIDEOURLGreaterThan(String value) {
            addCriterion("VIDEOURL >", value, "VIDEOURL");
            return (Criteria) this;
        }

        public Criteria andVIDEOURLGreaterThanOrEqualTo(String value) {
            addCriterion("VIDEOURL >=", value, "VIDEOURL");
            return (Criteria) this;
        }

        public Criteria andVIDEOURLLessThan(String value) {
            addCriterion("VIDEOURL <", value, "VIDEOURL");
            return (Criteria) this;
        }

        public Criteria andVIDEOURLLessThanOrEqualTo(String value) {
            addCriterion("VIDEOURL <=", value, "VIDEOURL");
            return (Criteria) this;
        }

        public Criteria andVIDEOURLLike(String value) {
            addCriterion("VIDEOURL like", value, "VIDEOURL");
            return (Criteria) this;
        }

        public Criteria andVIDEOURLNotLike(String value) {
            addCriterion("VIDEOURL not like", value, "VIDEOURL");
            return (Criteria) this;
        }

        public Criteria andVIDEOURLIn(List values) {
            addCriterion("VIDEOURL in", values, "VIDEOURL");
            return (Criteria) this;
        }

        public Criteria andVIDEOURLNotIn(List values) {
            addCriterion("VIDEOURL not in", values, "VIDEOURL");
            return (Criteria) this;
        }

        public Criteria andVIDEOURLBetween(String value1, String value2) {
            addCriterion("VIDEOURL between", value1, value2, "VIDEOURL");
            return (Criteria) this;
        }

        public Criteria andVIDEOURLNotBetween(String value1, String value2) {
            addCriterion("VIDEOURL not between", value1, value2, "VIDEOURL");
            return (Criteria) this;
        }

        public Criteria andISSUPERVISEDIsNull() {
            addCriterion("ISSUPERVISED is null");
            return (Criteria) this;
        }

        public Criteria andISSUPERVISEDIsNotNull() {
            addCriterion("ISSUPERVISED is not null");
            return (Criteria) this;
        }

        public Criteria andISSUPERVISEDEqualTo(BigDecimal value) {
            addCriterion("ISSUPERVISED =", value, "ISSUPERVISED");
            return (Criteria) this;
        }

        public Criteria andISSUPERVISEDNotEqualTo(BigDecimal value) {
            addCriterion("ISSUPERVISED <>", value, "ISSUPERVISED");
            return (Criteria) this;
        }

        public Criteria andISSUPERVISEDGreaterThan(BigDecimal value) {
            addCriterion("ISSUPERVISED >", value, "ISSUPERVISED");
            return (Criteria) this;
        }

        public Criteria andISSUPERVISEDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ISSUPERVISED >=", value, "ISSUPERVISED");
            return (Criteria) this;
        }

        public Criteria andISSUPERVISEDLessThan(BigDecimal value) {
            addCriterion("ISSUPERVISED <", value, "ISSUPERVISED");
            return (Criteria) this;
        }

        public Criteria andISSUPERVISEDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ISSUPERVISED <=", value, "ISSUPERVISED");
            return (Criteria) this;
        }

        public Criteria andISSUPERVISEDIn(List values) {
            addCriterion("ISSUPERVISED in", values, "ISSUPERVISED");
            return (Criteria) this;
        }

        public Criteria andISSUPERVISEDNotIn(List values) {
            addCriterion("ISSUPERVISED not in", values, "ISSUPERVISED");
            return (Criteria) this;
        }

        public Criteria andISSUPERVISEDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ISSUPERVISED between", value1, value2, "ISSUPERVISED");
            return (Criteria) this;
        }

        public Criteria andISSUPERVISEDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ISSUPERVISED not between", value1, value2, "ISSUPERVISED");
            return (Criteria) this;
        }

        public Criteria andREMARKIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andREMARKIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andREMARKEqualTo(String value) {
            addCriterion("REMARK =", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKGreaterThan(String value) {
            addCriterion("REMARK >", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKLessThan(String value) {
            addCriterion("REMARK <", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKLike(String value) {
            addCriterion("REMARK like", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotLike(String value) {
            addCriterion("REMARK not like", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKIn(List values) {
            addCriterion("REMARK in", values, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotIn(List values) {
            addCriterion("REMARK not in", values, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "REMARK");
            return (Criteria) this;
        }

        public Criteria andLASTGRADEDATEIsNull() {
            addCriterion("LASTGRADEDATE is null");
            return (Criteria) this;
        }

        public Criteria andLASTGRADEDATEIsNotNull() {
            addCriterion("LASTGRADEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andLASTGRADEDATEEqualTo(Date value) {
            addCriterion("LASTGRADEDATE =", value, "LASTGRADEDATE");
            return (Criteria) this;
        }

        public Criteria andLASTGRADEDATENotEqualTo(Date value) {
            addCriterion("LASTGRADEDATE <>", value, "LASTGRADEDATE");
            return (Criteria) this;
        }

        public Criteria andLASTGRADEDATEGreaterThan(Date value) {
            addCriterion("LASTGRADEDATE >", value, "LASTGRADEDATE");
            return (Criteria) this;
        }

        public Criteria andLASTGRADEDATEGreaterThanOrEqualTo(Date value) {
            addCriterion("LASTGRADEDATE >=", value, "LASTGRADEDATE");
            return (Criteria) this;
        }

        public Criteria andLASTGRADEDATELessThan(Date value) {
            addCriterion("LASTGRADEDATE <", value, "LASTGRADEDATE");
            return (Criteria) this;
        }

        public Criteria andLASTGRADEDATELessThanOrEqualTo(Date value) {
            addCriterion("LASTGRADEDATE <=", value, "LASTGRADEDATE");
            return (Criteria) this;
        }

        public Criteria andLASTGRADEDATEIn(List values) {
            addCriterion("LASTGRADEDATE in", values, "LASTGRADEDATE");
            return (Criteria) this;
        }

        public Criteria andLASTGRADEDATENotIn(List values) {
            addCriterion("LASTGRADEDATE not in", values, "LASTGRADEDATE");
            return (Criteria) this;
        }

        public Criteria andLASTGRADEDATEBetween(Date value1, Date value2) {
            addCriterion("LASTGRADEDATE between", value1, value2, "LASTGRADEDATE");
            return (Criteria) this;
        }

        public Criteria andLASTGRADEDATENotBetween(Date value1, Date value2) {
            addCriterion("LASTGRADEDATE not between", value1, value2, "LASTGRADEDATE");
            return (Criteria) this;
        }

        public Criteria andNATUREIsNull() {
            addCriterion("NATURE is null");
            return (Criteria) this;
        }

        public Criteria andNATUREIsNotNull() {
            addCriterion("NATURE is not null");
            return (Criteria) this;
        }

        public Criteria andNATUREEqualTo(String value) {
            addCriterion("NATURE =", value, "NATURE");
            return (Criteria) this;
        }

        public Criteria andNATURENotEqualTo(String value) {
            addCriterion("NATURE <>", value, "NATURE");
            return (Criteria) this;
        }

        public Criteria andNATUREGreaterThan(String value) {
            addCriterion("NATURE >", value, "NATURE");
            return (Criteria) this;
        }

        public Criteria andNATUREGreaterThanOrEqualTo(String value) {
            addCriterion("NATURE >=", value, "NATURE");
            return (Criteria) this;
        }

        public Criteria andNATURELessThan(String value) {
            addCriterion("NATURE <", value, "NATURE");
            return (Criteria) this;
        }

        public Criteria andNATURELessThanOrEqualTo(String value) {
            addCriterion("NATURE <=", value, "NATURE");
            return (Criteria) this;
        }

        public Criteria andNATURELike(String value) {
            addCriterion("NATURE like", value, "NATURE");
            return (Criteria) this;
        }

        public Criteria andNATURENotLike(String value) {
            addCriterion("NATURE not like", value, "NATURE");
            return (Criteria) this;
        }

        public Criteria andNATUREIn(List values) {
            addCriterion("NATURE in", values, "NATURE");
            return (Criteria) this;
        }

        public Criteria andNATURENotIn(List values) {
            addCriterion("NATURE not in", values, "NATURE");
            return (Criteria) this;
        }

        public Criteria andNATUREBetween(String value1, String value2) {
            addCriterion("NATURE between", value1, value2, "NATURE");
            return (Criteria) this;
        }

        public Criteria andNATURENotBetween(String value1, String value2) {
            addCriterion("NATURE not between", value1, value2, "NATURE");
            return (Criteria) this;
        }

        public Criteria andPEOPLECOUNTIsNull() {
            addCriterion("PEOPLECOUNT is null");
            return (Criteria) this;
        }

        public Criteria andPEOPLECOUNTIsNotNull() {
            addCriterion("PEOPLECOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andPEOPLECOUNTEqualTo(BigDecimal value) {
            addCriterion("PEOPLECOUNT =", value, "PEOPLECOUNT");
            return (Criteria) this;
        }

        public Criteria andPEOPLECOUNTNotEqualTo(BigDecimal value) {
            addCriterion("PEOPLECOUNT <>", value, "PEOPLECOUNT");
            return (Criteria) this;
        }

        public Criteria andPEOPLECOUNTGreaterThan(BigDecimal value) {
            addCriterion("PEOPLECOUNT >", value, "PEOPLECOUNT");
            return (Criteria) this;
        }

        public Criteria andPEOPLECOUNTGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PEOPLECOUNT >=", value, "PEOPLECOUNT");
            return (Criteria) this;
        }

        public Criteria andPEOPLECOUNTLessThan(BigDecimal value) {
            addCriterion("PEOPLECOUNT <", value, "PEOPLECOUNT");
            return (Criteria) this;
        }

        public Criteria andPEOPLECOUNTLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PEOPLECOUNT <=", value, "PEOPLECOUNT");
            return (Criteria) this;
        }

        public Criteria andPEOPLECOUNTIn(List values) {
            addCriterion("PEOPLECOUNT in", values, "PEOPLECOUNT");
            return (Criteria) this;
        }

        public Criteria andPEOPLECOUNTNotIn(List values) {
            addCriterion("PEOPLECOUNT not in", values, "PEOPLECOUNT");
            return (Criteria) this;
        }

        public Criteria andPEOPLECOUNTBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PEOPLECOUNT between", value1, value2, "PEOPLECOUNT");
            return (Criteria) this;
        }

        public Criteria andPEOPLECOUNTNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PEOPLECOUNT not between", value1, value2, "PEOPLECOUNT");
            return (Criteria) this;
        }

        public Criteria andRJOBTITLEIsNull() {
            addCriterion("RJOBTITLE is null");
            return (Criteria) this;
        }

        public Criteria andRJOBTITLEIsNotNull() {
            addCriterion("RJOBTITLE is not null");
            return (Criteria) this;
        }

        public Criteria andRJOBTITLEEqualTo(String value) {
            addCriterion("RJOBTITLE =", value, "RJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andRJOBTITLENotEqualTo(String value) {
            addCriterion("RJOBTITLE <>", value, "RJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andRJOBTITLEGreaterThan(String value) {
            addCriterion("RJOBTITLE >", value, "RJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andRJOBTITLEGreaterThanOrEqualTo(String value) {
            addCriterion("RJOBTITLE >=", value, "RJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andRJOBTITLELessThan(String value) {
            addCriterion("RJOBTITLE <", value, "RJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andRJOBTITLELessThanOrEqualTo(String value) {
            addCriterion("RJOBTITLE <=", value, "RJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andRJOBTITLELike(String value) {
            addCriterion("RJOBTITLE like", value, "RJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andRJOBTITLENotLike(String value) {
            addCriterion("RJOBTITLE not like", value, "RJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andRJOBTITLEIn(List values) {
            addCriterion("RJOBTITLE in", values, "RJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andRJOBTITLENotIn(List values) {
            addCriterion("RJOBTITLE not in", values, "RJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andRJOBTITLEBetween(String value1, String value2) {
            addCriterion("RJOBTITLE between", value1, value2, "RJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andRJOBTITLENotBetween(String value1, String value2) {
            addCriterion("RJOBTITLE not between", value1, value2, "RJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andRPHONENOIsNull() {
            addCriterion("RPHONENO is null");
            return (Criteria) this;
        }

        public Criteria andRPHONENOIsNotNull() {
            addCriterion("RPHONENO is not null");
            return (Criteria) this;
        }

        public Criteria andRPHONENOEqualTo(String value) {
            addCriterion("RPHONENO =", value, "RPHONENO");
            return (Criteria) this;
        }

        public Criteria andRPHONENONotEqualTo(String value) {
            addCriterion("RPHONENO <>", value, "RPHONENO");
            return (Criteria) this;
        }

        public Criteria andRPHONENOGreaterThan(String value) {
            addCriterion("RPHONENO >", value, "RPHONENO");
            return (Criteria) this;
        }

        public Criteria andRPHONENOGreaterThanOrEqualTo(String value) {
            addCriterion("RPHONENO >=", value, "RPHONENO");
            return (Criteria) this;
        }

        public Criteria andRPHONENOLessThan(String value) {
            addCriterion("RPHONENO <", value, "RPHONENO");
            return (Criteria) this;
        }

        public Criteria andRPHONENOLessThanOrEqualTo(String value) {
            addCriterion("RPHONENO <=", value, "RPHONENO");
            return (Criteria) this;
        }

        public Criteria andRPHONENOLike(String value) {
            addCriterion("RPHONENO like", value, "RPHONENO");
            return (Criteria) this;
        }

        public Criteria andRPHONENONotLike(String value) {
            addCriterion("RPHONENO not like", value, "RPHONENO");
            return (Criteria) this;
        }

        public Criteria andRPHONENOIn(List values) {
            addCriterion("RPHONENO in", values, "RPHONENO");
            return (Criteria) this;
        }

        public Criteria andRPHONENONotIn(List values) {
            addCriterion("RPHONENO not in", values, "RPHONENO");
            return (Criteria) this;
        }

        public Criteria andRPHONENOBetween(String value1, String value2) {
            addCriterion("RPHONENO between", value1, value2, "RPHONENO");
            return (Criteria) this;
        }

        public Criteria andRPHONENONotBetween(String value1, String value2) {
            addCriterion("RPHONENO not between", value1, value2, "RPHONENO");
            return (Criteria) this;
        }

        public Criteria andRPOSTIsNull() {
            addCriterion("RPOST is null");
            return (Criteria) this;
        }

        public Criteria andRPOSTIsNotNull() {
            addCriterion("RPOST is not null");
            return (Criteria) this;
        }

        public Criteria andRPOSTEqualTo(String value) {
            addCriterion("RPOST =", value, "RPOST");
            return (Criteria) this;
        }

        public Criteria andRPOSTNotEqualTo(String value) {
            addCriterion("RPOST <>", value, "RPOST");
            return (Criteria) this;
        }

        public Criteria andRPOSTGreaterThan(String value) {
            addCriterion("RPOST >", value, "RPOST");
            return (Criteria) this;
        }

        public Criteria andRPOSTGreaterThanOrEqualTo(String value) {
            addCriterion("RPOST >=", value, "RPOST");
            return (Criteria) this;
        }

        public Criteria andRPOSTLessThan(String value) {
            addCriterion("RPOST <", value, "RPOST");
            return (Criteria) this;
        }

        public Criteria andRPOSTLessThanOrEqualTo(String value) {
            addCriterion("RPOST <=", value, "RPOST");
            return (Criteria) this;
        }

        public Criteria andRPOSTLike(String value) {
            addCriterion("RPOST like", value, "RPOST");
            return (Criteria) this;
        }

        public Criteria andRPOSTNotLike(String value) {
            addCriterion("RPOST not like", value, "RPOST");
            return (Criteria) this;
        }

        public Criteria andRPOSTIn(List values) {
            addCriterion("RPOST in", values, "RPOST");
            return (Criteria) this;
        }

        public Criteria andRPOSTNotIn(List values) {
            addCriterion("RPOST not in", values, "RPOST");
            return (Criteria) this;
        }

        public Criteria andRPOSTBetween(String value1, String value2) {
            addCriterion("RPOST between", value1, value2, "RPOST");
            return (Criteria) this;
        }

        public Criteria andRPOSTNotBetween(String value1, String value2) {
            addCriterion("RPOST not between", value1, value2, "RPOST");
            return (Criteria) this;
        }

        public Criteria andLEGALPERSONIsNull() {
            addCriterion("LEGALPERSON is null");
            return (Criteria) this;
        }

        public Criteria andLEGALPERSONIsNotNull() {
            addCriterion("LEGALPERSON is not null");
            return (Criteria) this;
        }

        public Criteria andLEGALPERSONEqualTo(String value) {
            addCriterion("LEGALPERSON =", value, "LEGALPERSON");
            return (Criteria) this;
        }

        public Criteria andLEGALPERSONNotEqualTo(String value) {
            addCriterion("LEGALPERSON <>", value, "LEGALPERSON");
            return (Criteria) this;
        }

        public Criteria andLEGALPERSONGreaterThan(String value) {
            addCriterion("LEGALPERSON >", value, "LEGALPERSON");
            return (Criteria) this;
        }

        public Criteria andLEGALPERSONGreaterThanOrEqualTo(String value) {
            addCriterion("LEGALPERSON >=", value, "LEGALPERSON");
            return (Criteria) this;
        }

        public Criteria andLEGALPERSONLessThan(String value) {
            addCriterion("LEGALPERSON <", value, "LEGALPERSON");
            return (Criteria) this;
        }

        public Criteria andLEGALPERSONLessThanOrEqualTo(String value) {
            addCriterion("LEGALPERSON <=", value, "LEGALPERSON");
            return (Criteria) this;
        }

        public Criteria andLEGALPERSONLike(String value) {
            addCriterion("LEGALPERSON like", value, "LEGALPERSON");
            return (Criteria) this;
        }

        public Criteria andLEGALPERSONNotLike(String value) {
            addCriterion("LEGALPERSON not like", value, "LEGALPERSON");
            return (Criteria) this;
        }

        public Criteria andLEGALPERSONIn(List values) {
            addCriterion("LEGALPERSON in", values, "LEGALPERSON");
            return (Criteria) this;
        }

        public Criteria andLEGALPERSONNotIn(List values) {
            addCriterion("LEGALPERSON not in", values, "LEGALPERSON");
            return (Criteria) this;
        }

        public Criteria andLEGALPERSONBetween(String value1, String value2) {
            addCriterion("LEGALPERSON between", value1, value2, "LEGALPERSON");
            return (Criteria) this;
        }

        public Criteria andLEGALPERSONNotBetween(String value1, String value2) {
            addCriterion("LEGALPERSON not between", value1, value2, "LEGALPERSON");
            return (Criteria) this;
        }

        public Criteria andLJOBTITLEIsNull() {
            addCriterion("LJOBTITLE is null");
            return (Criteria) this;
        }

        public Criteria andLJOBTITLEIsNotNull() {
            addCriterion("LJOBTITLE is not null");
            return (Criteria) this;
        }

        public Criteria andLJOBTITLEEqualTo(String value) {
            addCriterion("LJOBTITLE =", value, "LJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andLJOBTITLENotEqualTo(String value) {
            addCriterion("LJOBTITLE <>", value, "LJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andLJOBTITLEGreaterThan(String value) {
            addCriterion("LJOBTITLE >", value, "LJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andLJOBTITLEGreaterThanOrEqualTo(String value) {
            addCriterion("LJOBTITLE >=", value, "LJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andLJOBTITLELessThan(String value) {
            addCriterion("LJOBTITLE <", value, "LJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andLJOBTITLELessThanOrEqualTo(String value) {
            addCriterion("LJOBTITLE <=", value, "LJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andLJOBTITLELike(String value) {
            addCriterion("LJOBTITLE like", value, "LJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andLJOBTITLENotLike(String value) {
            addCriterion("LJOBTITLE not like", value, "LJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andLJOBTITLEIn(List values) {
            addCriterion("LJOBTITLE in", values, "LJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andLJOBTITLENotIn(List values) {
            addCriterion("LJOBTITLE not in", values, "LJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andLJOBTITLEBetween(String value1, String value2) {
            addCriterion("LJOBTITLE between", value1, value2, "LJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andLJOBTITLENotBetween(String value1, String value2) {
            addCriterion("LJOBTITLE not between", value1, value2, "LJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andLPHONENOIsNull() {
            addCriterion("LPHONENO is null");
            return (Criteria) this;
        }

        public Criteria andLPHONENOIsNotNull() {
            addCriterion("LPHONENO is not null");
            return (Criteria) this;
        }

        public Criteria andLPHONENOEqualTo(String value) {
            addCriterion("LPHONENO =", value, "LPHONENO");
            return (Criteria) this;
        }

        public Criteria andLPHONENONotEqualTo(String value) {
            addCriterion("LPHONENO <>", value, "LPHONENO");
            return (Criteria) this;
        }

        public Criteria andLPHONENOGreaterThan(String value) {
            addCriterion("LPHONENO >", value, "LPHONENO");
            return (Criteria) this;
        }

        public Criteria andLPHONENOGreaterThanOrEqualTo(String value) {
            addCriterion("LPHONENO >=", value, "LPHONENO");
            return (Criteria) this;
        }

        public Criteria andLPHONENOLessThan(String value) {
            addCriterion("LPHONENO <", value, "LPHONENO");
            return (Criteria) this;
        }

        public Criteria andLPHONENOLessThanOrEqualTo(String value) {
            addCriterion("LPHONENO <=", value, "LPHONENO");
            return (Criteria) this;
        }

        public Criteria andLPHONENOLike(String value) {
            addCriterion("LPHONENO like", value, "LPHONENO");
            return (Criteria) this;
        }

        public Criteria andLPHONENONotLike(String value) {
            addCriterion("LPHONENO not like", value, "LPHONENO");
            return (Criteria) this;
        }

        public Criteria andLPHONENOIn(List values) {
            addCriterion("LPHONENO in", values, "LPHONENO");
            return (Criteria) this;
        }

        public Criteria andLPHONENONotIn(List values) {
            addCriterion("LPHONENO not in", values, "LPHONENO");
            return (Criteria) this;
        }

        public Criteria andLPHONENOBetween(String value1, String value2) {
            addCriterion("LPHONENO between", value1, value2, "LPHONENO");
            return (Criteria) this;
        }

        public Criteria andLPHONENONotBetween(String value1, String value2) {
            addCriterion("LPHONENO not between", value1, value2, "LPHONENO");
            return (Criteria) this;
        }

        public Criteria andLPOSTIsNull() {
            addCriterion("LPOST is null");
            return (Criteria) this;
        }

        public Criteria andLPOSTIsNotNull() {
            addCriterion("LPOST is not null");
            return (Criteria) this;
        }

        public Criteria andLPOSTEqualTo(String value) {
            addCriterion("LPOST =", value, "LPOST");
            return (Criteria) this;
        }

        public Criteria andLPOSTNotEqualTo(String value) {
            addCriterion("LPOST <>", value, "LPOST");
            return (Criteria) this;
        }

        public Criteria andLPOSTGreaterThan(String value) {
            addCriterion("LPOST >", value, "LPOST");
            return (Criteria) this;
        }

        public Criteria andLPOSTGreaterThanOrEqualTo(String value) {
            addCriterion("LPOST >=", value, "LPOST");
            return (Criteria) this;
        }

        public Criteria andLPOSTLessThan(String value) {
            addCriterion("LPOST <", value, "LPOST");
            return (Criteria) this;
        }

        public Criteria andLPOSTLessThanOrEqualTo(String value) {
            addCriterion("LPOST <=", value, "LPOST");
            return (Criteria) this;
        }

        public Criteria andLPOSTLike(String value) {
            addCriterion("LPOST like", value, "LPOST");
            return (Criteria) this;
        }

        public Criteria andLPOSTNotLike(String value) {
            addCriterion("LPOST not like", value, "LPOST");
            return (Criteria) this;
        }

        public Criteria andLPOSTIn(List values) {
            addCriterion("LPOST in", values, "LPOST");
            return (Criteria) this;
        }

        public Criteria andLPOSTNotIn(List values) {
            addCriterion("LPOST not in", values, "LPOST");
            return (Criteria) this;
        }

        public Criteria andLPOSTBetween(String value1, String value2) {
            addCriterion("LPOST between", value1, value2, "LPOST");
            return (Criteria) this;
        }

        public Criteria andLPOSTNotBetween(String value1, String value2) {
            addCriterion("LPOST not between", value1, value2, "LPOST");
            return (Criteria) this;
        }

        public Criteria andQUALITYPERSONIsNull() {
            addCriterion("QUALITYPERSON is null");
            return (Criteria) this;
        }

        public Criteria andQUALITYPERSONIsNotNull() {
            addCriterion("QUALITYPERSON is not null");
            return (Criteria) this;
        }

        public Criteria andQUALITYPERSONEqualTo(String value) {
            addCriterion("QUALITYPERSON =", value, "QUALITYPERSON");
            return (Criteria) this;
        }

        public Criteria andQUALITYPERSONNotEqualTo(String value) {
            addCriterion("QUALITYPERSON <>", value, "QUALITYPERSON");
            return (Criteria) this;
        }

        public Criteria andQUALITYPERSONGreaterThan(String value) {
            addCriterion("QUALITYPERSON >", value, "QUALITYPERSON");
            return (Criteria) this;
        }

        public Criteria andQUALITYPERSONGreaterThanOrEqualTo(String value) {
            addCriterion("QUALITYPERSON >=", value, "QUALITYPERSON");
            return (Criteria) this;
        }

        public Criteria andQUALITYPERSONLessThan(String value) {
            addCriterion("QUALITYPERSON <", value, "QUALITYPERSON");
            return (Criteria) this;
        }

        public Criteria andQUALITYPERSONLessThanOrEqualTo(String value) {
            addCriterion("QUALITYPERSON <=", value, "QUALITYPERSON");
            return (Criteria) this;
        }

        public Criteria andQUALITYPERSONLike(String value) {
            addCriterion("QUALITYPERSON like", value, "QUALITYPERSON");
            return (Criteria) this;
        }

        public Criteria andQUALITYPERSONNotLike(String value) {
            addCriterion("QUALITYPERSON not like", value, "QUALITYPERSON");
            return (Criteria) this;
        }

        public Criteria andQUALITYPERSONIn(List values) {
            addCriterion("QUALITYPERSON in", values, "QUALITYPERSON");
            return (Criteria) this;
        }

        public Criteria andQUALITYPERSONNotIn(List values) {
            addCriterion("QUALITYPERSON not in", values, "QUALITYPERSON");
            return (Criteria) this;
        }

        public Criteria andQUALITYPERSONBetween(String value1, String value2) {
            addCriterion("QUALITYPERSON between", value1, value2, "QUALITYPERSON");
            return (Criteria) this;
        }

        public Criteria andQUALITYPERSONNotBetween(String value1, String value2) {
            addCriterion("QUALITYPERSON not between", value1, value2, "QUALITYPERSON");
            return (Criteria) this;
        }

        public Criteria andQJOBTITLEIsNull() {
            addCriterion("QJOBTITLE is null");
            return (Criteria) this;
        }

        public Criteria andQJOBTITLEIsNotNull() {
            addCriterion("QJOBTITLE is not null");
            return (Criteria) this;
        }

        public Criteria andQJOBTITLEEqualTo(String value) {
            addCriterion("QJOBTITLE =", value, "QJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andQJOBTITLENotEqualTo(String value) {
            addCriterion("QJOBTITLE <>", value, "QJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andQJOBTITLEGreaterThan(String value) {
            addCriterion("QJOBTITLE >", value, "QJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andQJOBTITLEGreaterThanOrEqualTo(String value) {
            addCriterion("QJOBTITLE >=", value, "QJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andQJOBTITLELessThan(String value) {
            addCriterion("QJOBTITLE <", value, "QJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andQJOBTITLELessThanOrEqualTo(String value) {
            addCriterion("QJOBTITLE <=", value, "QJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andQJOBTITLELike(String value) {
            addCriterion("QJOBTITLE like", value, "QJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andQJOBTITLENotLike(String value) {
            addCriterion("QJOBTITLE not like", value, "QJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andQJOBTITLEIn(List values) {
            addCriterion("QJOBTITLE in", values, "QJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andQJOBTITLENotIn(List values) {
            addCriterion("QJOBTITLE not in", values, "QJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andQJOBTITLEBetween(String value1, String value2) {
            addCriterion("QJOBTITLE between", value1, value2, "QJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andQJOBTITLENotBetween(String value1, String value2) {
            addCriterion("QJOBTITLE not between", value1, value2, "QJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andQPHONENOIsNull() {
            addCriterion("QPHONENO is null");
            return (Criteria) this;
        }

        public Criteria andQPHONENOIsNotNull() {
            addCriterion("QPHONENO is not null");
            return (Criteria) this;
        }

        public Criteria andQPHONENOEqualTo(String value) {
            addCriterion("QPHONENO =", value, "QPHONENO");
            return (Criteria) this;
        }

        public Criteria andQPHONENONotEqualTo(String value) {
            addCriterion("QPHONENO <>", value, "QPHONENO");
            return (Criteria) this;
        }

        public Criteria andQPHONENOGreaterThan(String value) {
            addCriterion("QPHONENO >", value, "QPHONENO");
            return (Criteria) this;
        }

        public Criteria andQPHONENOGreaterThanOrEqualTo(String value) {
            addCriterion("QPHONENO >=", value, "QPHONENO");
            return (Criteria) this;
        }

        public Criteria andQPHONENOLessThan(String value) {
            addCriterion("QPHONENO <", value, "QPHONENO");
            return (Criteria) this;
        }

        public Criteria andQPHONENOLessThanOrEqualTo(String value) {
            addCriterion("QPHONENO <=", value, "QPHONENO");
            return (Criteria) this;
        }

        public Criteria andQPHONENOLike(String value) {
            addCriterion("QPHONENO like", value, "QPHONENO");
            return (Criteria) this;
        }

        public Criteria andQPHONENONotLike(String value) {
            addCriterion("QPHONENO not like", value, "QPHONENO");
            return (Criteria) this;
        }

        public Criteria andQPHONENOIn(List values) {
            addCriterion("QPHONENO in", values, "QPHONENO");
            return (Criteria) this;
        }

        public Criteria andQPHONENONotIn(List values) {
            addCriterion("QPHONENO not in", values, "QPHONENO");
            return (Criteria) this;
        }

        public Criteria andQPHONENOBetween(String value1, String value2) {
            addCriterion("QPHONENO between", value1, value2, "QPHONENO");
            return (Criteria) this;
        }

        public Criteria andQPHONENONotBetween(String value1, String value2) {
            addCriterion("QPHONENO not between", value1, value2, "QPHONENO");
            return (Criteria) this;
        }

        public Criteria andQPOSTIsNull() {
            addCriterion("QPOST is null");
            return (Criteria) this;
        }

        public Criteria andQPOSTIsNotNull() {
            addCriterion("QPOST is not null");
            return (Criteria) this;
        }

        public Criteria andQPOSTEqualTo(String value) {
            addCriterion("QPOST =", value, "QPOST");
            return (Criteria) this;
        }

        public Criteria andQPOSTNotEqualTo(String value) {
            addCriterion("QPOST <>", value, "QPOST");
            return (Criteria) this;
        }

        public Criteria andQPOSTGreaterThan(String value) {
            addCriterion("QPOST >", value, "QPOST");
            return (Criteria) this;
        }

        public Criteria andQPOSTGreaterThanOrEqualTo(String value) {
            addCriterion("QPOST >=", value, "QPOST");
            return (Criteria) this;
        }

        public Criteria andQPOSTLessThan(String value) {
            addCriterion("QPOST <", value, "QPOST");
            return (Criteria) this;
        }

        public Criteria andQPOSTLessThanOrEqualTo(String value) {
            addCriterion("QPOST <=", value, "QPOST");
            return (Criteria) this;
        }

        public Criteria andQPOSTLike(String value) {
            addCriterion("QPOST like", value, "QPOST");
            return (Criteria) this;
        }

        public Criteria andQPOSTNotLike(String value) {
            addCriterion("QPOST not like", value, "QPOST");
            return (Criteria) this;
        }

        public Criteria andQPOSTIn(List values) {
            addCriterion("QPOST in", values, "QPOST");
            return (Criteria) this;
        }

        public Criteria andQPOSTNotIn(List values) {
            addCriterion("QPOST not in", values, "QPOST");
            return (Criteria) this;
        }

        public Criteria andQPOSTBetween(String value1, String value2) {
            addCriterion("QPOST between", value1, value2, "QPOST");
            return (Criteria) this;
        }

        public Criteria andQPOSTNotBetween(String value1, String value2) {
            addCriterion("QPOST not between", value1, value2, "QPOST");
            return (Criteria) this;
        }

        public Criteria andDRUGCHECKPERSONIsNull() {
            addCriterion("DRUGCHECKPERSON is null");
            return (Criteria) this;
        }

        public Criteria andDRUGCHECKPERSONIsNotNull() {
            addCriterion("DRUGCHECKPERSON is not null");
            return (Criteria) this;
        }

        public Criteria andDRUGCHECKPERSONEqualTo(String value) {
            addCriterion("DRUGCHECKPERSON =", value, "DRUGCHECKPERSON");
            return (Criteria) this;
        }

        public Criteria andDRUGCHECKPERSONNotEqualTo(String value) {
            addCriterion("DRUGCHECKPERSON <>", value, "DRUGCHECKPERSON");
            return (Criteria) this;
        }

        public Criteria andDRUGCHECKPERSONGreaterThan(String value) {
            addCriterion("DRUGCHECKPERSON >", value, "DRUGCHECKPERSON");
            return (Criteria) this;
        }

        public Criteria andDRUGCHECKPERSONGreaterThanOrEqualTo(String value) {
            addCriterion("DRUGCHECKPERSON >=", value, "DRUGCHECKPERSON");
            return (Criteria) this;
        }

        public Criteria andDRUGCHECKPERSONLessThan(String value) {
            addCriterion("DRUGCHECKPERSON <", value, "DRUGCHECKPERSON");
            return (Criteria) this;
        }

        public Criteria andDRUGCHECKPERSONLessThanOrEqualTo(String value) {
            addCriterion("DRUGCHECKPERSON <=", value, "DRUGCHECKPERSON");
            return (Criteria) this;
        }

        public Criteria andDRUGCHECKPERSONLike(String value) {
            addCriterion("DRUGCHECKPERSON like", value, "DRUGCHECKPERSON");
            return (Criteria) this;
        }

        public Criteria andDRUGCHECKPERSONNotLike(String value) {
            addCriterion("DRUGCHECKPERSON not like", value, "DRUGCHECKPERSON");
            return (Criteria) this;
        }

        public Criteria andDRUGCHECKPERSONIn(List values) {
            addCriterion("DRUGCHECKPERSON in", values, "DRUGCHECKPERSON");
            return (Criteria) this;
        }

        public Criteria andDRUGCHECKPERSONNotIn(List values) {
            addCriterion("DRUGCHECKPERSON not in", values, "DRUGCHECKPERSON");
            return (Criteria) this;
        }

        public Criteria andDRUGCHECKPERSONBetween(String value1, String value2) {
            addCriterion("DRUGCHECKPERSON between", value1, value2, "DRUGCHECKPERSON");
            return (Criteria) this;
        }

        public Criteria andDRUGCHECKPERSONNotBetween(String value1, String value2) {
            addCriterion("DRUGCHECKPERSON not between", value1, value2, "DRUGCHECKPERSON");
            return (Criteria) this;
        }

        public Criteria andDJOBTITLEIsNull() {
            addCriterion("DJOBTITLE is null");
            return (Criteria) this;
        }

        public Criteria andDJOBTITLEIsNotNull() {
            addCriterion("DJOBTITLE is not null");
            return (Criteria) this;
        }

        public Criteria andDJOBTITLEEqualTo(String value) {
            addCriterion("DJOBTITLE =", value, "DJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andDJOBTITLENotEqualTo(String value) {
            addCriterion("DJOBTITLE <>", value, "DJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andDJOBTITLEGreaterThan(String value) {
            addCriterion("DJOBTITLE >", value, "DJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andDJOBTITLEGreaterThanOrEqualTo(String value) {
            addCriterion("DJOBTITLE >=", value, "DJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andDJOBTITLELessThan(String value) {
            addCriterion("DJOBTITLE <", value, "DJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andDJOBTITLELessThanOrEqualTo(String value) {
            addCriterion("DJOBTITLE <=", value, "DJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andDJOBTITLELike(String value) {
            addCriterion("DJOBTITLE like", value, "DJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andDJOBTITLENotLike(String value) {
            addCriterion("DJOBTITLE not like", value, "DJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andDJOBTITLEIn(List values) {
            addCriterion("DJOBTITLE in", values, "DJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andDJOBTITLENotIn(List values) {
            addCriterion("DJOBTITLE not in", values, "DJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andDJOBTITLEBetween(String value1, String value2) {
            addCriterion("DJOBTITLE between", value1, value2, "DJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andDJOBTITLENotBetween(String value1, String value2) {
            addCriterion("DJOBTITLE not between", value1, value2, "DJOBTITLE");
            return (Criteria) this;
        }

        public Criteria andDPHONENOIsNull() {
            addCriterion("DPHONENO is null");
            return (Criteria) this;
        }

        public Criteria andDPHONENOIsNotNull() {
            addCriterion("DPHONENO is not null");
            return (Criteria) this;
        }

        public Criteria andDPHONENOEqualTo(String value) {
            addCriterion("DPHONENO =", value, "DPHONENO");
            return (Criteria) this;
        }

        public Criteria andDPHONENONotEqualTo(String value) {
            addCriterion("DPHONENO <>", value, "DPHONENO");
            return (Criteria) this;
        }

        public Criteria andDPHONENOGreaterThan(String value) {
            addCriterion("DPHONENO >", value, "DPHONENO");
            return (Criteria) this;
        }

        public Criteria andDPHONENOGreaterThanOrEqualTo(String value) {
            addCriterion("DPHONENO >=", value, "DPHONENO");
            return (Criteria) this;
        }

        public Criteria andDPHONENOLessThan(String value) {
            addCriterion("DPHONENO <", value, "DPHONENO");
            return (Criteria) this;
        }

        public Criteria andDPHONENOLessThanOrEqualTo(String value) {
            addCriterion("DPHONENO <=", value, "DPHONENO");
            return (Criteria) this;
        }

        public Criteria andDPHONENOLike(String value) {
            addCriterion("DPHONENO like", value, "DPHONENO");
            return (Criteria) this;
        }

        public Criteria andDPHONENONotLike(String value) {
            addCriterion("DPHONENO not like", value, "DPHONENO");
            return (Criteria) this;
        }

        public Criteria andDPHONENOIn(List values) {
            addCriterion("DPHONENO in", values, "DPHONENO");
            return (Criteria) this;
        }

        public Criteria andDPHONENONotIn(List values) {
            addCriterion("DPHONENO not in", values, "DPHONENO");
            return (Criteria) this;
        }

        public Criteria andDPHONENOBetween(String value1, String value2) {
            addCriterion("DPHONENO between", value1, value2, "DPHONENO");
            return (Criteria) this;
        }

        public Criteria andDPHONENONotBetween(String value1, String value2) {
            addCriterion("DPHONENO not between", value1, value2, "DPHONENO");
            return (Criteria) this;
        }

        public Criteria andDPOSTIsNull() {
            addCriterion("DPOST is null");
            return (Criteria) this;
        }

        public Criteria andDPOSTIsNotNull() {
            addCriterion("DPOST is not null");
            return (Criteria) this;
        }

        public Criteria andDPOSTEqualTo(String value) {
            addCriterion("DPOST =", value, "DPOST");
            return (Criteria) this;
        }

        public Criteria andDPOSTNotEqualTo(String value) {
            addCriterion("DPOST <>", value, "DPOST");
            return (Criteria) this;
        }

        public Criteria andDPOSTGreaterThan(String value) {
            addCriterion("DPOST >", value, "DPOST");
            return (Criteria) this;
        }

        public Criteria andDPOSTGreaterThanOrEqualTo(String value) {
            addCriterion("DPOST >=", value, "DPOST");
            return (Criteria) this;
        }

        public Criteria andDPOSTLessThan(String value) {
            addCriterion("DPOST <", value, "DPOST");
            return (Criteria) this;
        }

        public Criteria andDPOSTLessThanOrEqualTo(String value) {
            addCriterion("DPOST <=", value, "DPOST");
            return (Criteria) this;
        }

        public Criteria andDPOSTLike(String value) {
            addCriterion("DPOST like", value, "DPOST");
            return (Criteria) this;
        }

        public Criteria andDPOSTNotLike(String value) {
            addCriterion("DPOST not like", value, "DPOST");
            return (Criteria) this;
        }

        public Criteria andDPOSTIn(List values) {
            addCriterion("DPOST in", values, "DPOST");
            return (Criteria) this;
        }

        public Criteria andDPOSTNotIn(List values) {
            addCriterion("DPOST not in", values, "DPOST");
            return (Criteria) this;
        }

        public Criteria andDPOSTBetween(String value1, String value2) {
            addCriterion("DPOST between", value1, value2, "DPOST");
            return (Criteria) this;
        }

        public Criteria andDPOSTNotBetween(String value1, String value2) {
            addCriterion("DPOST not between", value1, value2, "DPOST");
            return (Criteria) this;
        }

        public Criteria andOTHERPEOPLEIsNull() {
            addCriterion("OTHERPEOPLE is null");
            return (Criteria) this;
        }

        public Criteria andOTHERPEOPLEIsNotNull() {
            addCriterion("OTHERPEOPLE is not null");
            return (Criteria) this;
        }

        public Criteria andOTHERPEOPLEEqualTo(String value) {
            addCriterion("OTHERPEOPLE =", value, "OTHERPEOPLE");
            return (Criteria) this;
        }

        public Criteria andOTHERPEOPLENotEqualTo(String value) {
            addCriterion("OTHERPEOPLE <>", value, "OTHERPEOPLE");
            return (Criteria) this;
        }

        public Criteria andOTHERPEOPLEGreaterThan(String value) {
            addCriterion("OTHERPEOPLE >", value, "OTHERPEOPLE");
            return (Criteria) this;
        }

        public Criteria andOTHERPEOPLEGreaterThanOrEqualTo(String value) {
            addCriterion("OTHERPEOPLE >=", value, "OTHERPEOPLE");
            return (Criteria) this;
        }

        public Criteria andOTHERPEOPLELessThan(String value) {
            addCriterion("OTHERPEOPLE <", value, "OTHERPEOPLE");
            return (Criteria) this;
        }

        public Criteria andOTHERPEOPLELessThanOrEqualTo(String value) {
            addCriterion("OTHERPEOPLE <=", value, "OTHERPEOPLE");
            return (Criteria) this;
        }

        public Criteria andOTHERPEOPLELike(String value) {
            addCriterion("OTHERPEOPLE like", value, "OTHERPEOPLE");
            return (Criteria) this;
        }

        public Criteria andOTHERPEOPLENotLike(String value) {
            addCriterion("OTHERPEOPLE not like", value, "OTHERPEOPLE");
            return (Criteria) this;
        }

        public Criteria andOTHERPEOPLEIn(List values) {
            addCriterion("OTHERPEOPLE in", values, "OTHERPEOPLE");
            return (Criteria) this;
        }

        public Criteria andOTHERPEOPLENotIn(List values) {
            addCriterion("OTHERPEOPLE not in", values, "OTHERPEOPLE");
            return (Criteria) this;
        }

        public Criteria andOTHERPEOPLEBetween(String value1, String value2) {
            addCriterion("OTHERPEOPLE between", value1, value2, "OTHERPEOPLE");
            return (Criteria) this;
        }

        public Criteria andOTHERPEOPLENotBetween(String value1, String value2) {
            addCriterion("OTHERPEOPLE not between", value1, value2, "OTHERPEOPLE");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DRUGSTORE
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 16 09:15:22 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}