package com.wildwolf.model;

import java.math.BigDecimal;
import java.util.Date;

import com.wildwolf.helper.page.Page;

public class Drugstore extends Page{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.DRUGSTOREID
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String DRUGSTOREID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.BUSINESSOPERATIONID
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String BUSINESSOPERATIONID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.DSNAME
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String DSNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.ADDRESS
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String ADDRESS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.RESPONSIBLEPERSON
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String RESPONSIBLEPERSON;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.CREATEDATE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private Date CREATEDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.CREATEBY
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String CREATEBY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.TEL
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String TEL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.REGION
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String REGION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.BUSINESSMODEL
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String BUSINESSMODEL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.BUSINESSSCOPE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String BUSINESSSCOPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.FAX
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String FAX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.VIDEOURL
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String VIDEOURL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.ISSUPERVISED
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private BigDecimal ISSUPERVISED;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.REMARK
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String REMARK;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.LASTGRADEDATE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private Date LASTGRADEDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.NATURE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String NATURE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.PEOPLECOUNT
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private BigDecimal PEOPLECOUNT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.RJOBTITLE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String RJOBTITLE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.RPHONENO
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String RPHONENO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.RPOST
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String RPOST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.LEGALPERSON
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String LEGALPERSON;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.LJOBTITLE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String LJOBTITLE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.LPHONENO
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String LPHONENO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.LPOST
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String LPOST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.QUALITYPERSON
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String QUALITYPERSON;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.QJOBTITLE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String QJOBTITLE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.QPHONENO
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String QPHONENO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.QPOST
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String QPOST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.DRUGCHECKPERSON
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String DRUGCHECKPERSON;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.DJOBTITLE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String DJOBTITLE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.DPHONENO
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String DPHONENO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.DPOST
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String DPOST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRUGSTORE.OTHERPEOPLE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    private String OTHERPEOPLE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.DRUGSTOREID
     *
     * @return the value of DRUGSTORE.DRUGSTOREID
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getDRUGSTOREID() {
        return DRUGSTOREID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.DRUGSTOREID
     *
     * @param DRUGSTOREID the value for DRUGSTORE.DRUGSTOREID
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setDRUGSTOREID(String DRUGSTOREID) {
        this.DRUGSTOREID = DRUGSTOREID == null ? null : DRUGSTOREID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.BUSINESSOPERATIONID
     *
     * @return the value of DRUGSTORE.BUSINESSOPERATIONID
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getBUSINESSOPERATIONID() {
        return BUSINESSOPERATIONID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.BUSINESSOPERATIONID
     *
     * @param BUSINESSOPERATIONID the value for DRUGSTORE.BUSINESSOPERATIONID
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setBUSINESSOPERATIONID(String BUSINESSOPERATIONID) {
        this.BUSINESSOPERATIONID = BUSINESSOPERATIONID == null ? null : BUSINESSOPERATIONID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.DSNAME
     *
     * @return the value of DRUGSTORE.DSNAME
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getDSNAME() {
        return DSNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.DSNAME
     *
     * @param DSNAME the value for DRUGSTORE.DSNAME
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setDSNAME(String DSNAME) {
        this.DSNAME = DSNAME == null ? null : DSNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.ADDRESS
     *
     * @return the value of DRUGSTORE.ADDRESS
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getADDRESS() {
        return ADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.ADDRESS
     *
     * @param ADDRESS the value for DRUGSTORE.ADDRESS
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setADDRESS(String ADDRESS) {
        this.ADDRESS = ADDRESS == null ? null : ADDRESS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.RESPONSIBLEPERSON
     *
     * @return the value of DRUGSTORE.RESPONSIBLEPERSON
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getRESPONSIBLEPERSON() {
        return RESPONSIBLEPERSON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.RESPONSIBLEPERSON
     *
     * @param RESPONSIBLEPERSON the value for DRUGSTORE.RESPONSIBLEPERSON
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setRESPONSIBLEPERSON(String RESPONSIBLEPERSON) {
        this.RESPONSIBLEPERSON = RESPONSIBLEPERSON == null ? null : RESPONSIBLEPERSON.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.CREATEDATE
     *
     * @return the value of DRUGSTORE.CREATEDATE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public Date getCREATEDATE() {
        return CREATEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.CREATEDATE
     *
     * @param CREATEDATE the value for DRUGSTORE.CREATEDATE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setCREATEDATE(Date CREATEDATE) {
        this.CREATEDATE = CREATEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.CREATEBY
     *
     * @return the value of DRUGSTORE.CREATEBY
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getCREATEBY() {
        return CREATEBY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.CREATEBY
     *
     * @param CREATEBY the value for DRUGSTORE.CREATEBY
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setCREATEBY(String CREATEBY) {
        this.CREATEBY = CREATEBY == null ? null : CREATEBY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.TEL
     *
     * @return the value of DRUGSTORE.TEL
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getTEL() {
        return TEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.TEL
     *
     * @param TEL the value for DRUGSTORE.TEL
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setTEL(String TEL) {
        this.TEL = TEL == null ? null : TEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.REGION
     *
     * @return the value of DRUGSTORE.REGION
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getREGION() {
        return REGION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.REGION
     *
     * @param REGION the value for DRUGSTORE.REGION
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setREGION(String REGION) {
        this.REGION = REGION == null ? null : REGION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.BUSINESSMODEL
     *
     * @return the value of DRUGSTORE.BUSINESSMODEL
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getBUSINESSMODEL() {
        return BUSINESSMODEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.BUSINESSMODEL
     *
     * @param BUSINESSMODEL the value for DRUGSTORE.BUSINESSMODEL
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setBUSINESSMODEL(String BUSINESSMODEL) {
        this.BUSINESSMODEL = BUSINESSMODEL == null ? null : BUSINESSMODEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.BUSINESSSCOPE
     *
     * @return the value of DRUGSTORE.BUSINESSSCOPE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getBUSINESSSCOPE() {
        return BUSINESSSCOPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.BUSINESSSCOPE
     *
     * @param BUSINESSSCOPE the value for DRUGSTORE.BUSINESSSCOPE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setBUSINESSSCOPE(String BUSINESSSCOPE) {
        this.BUSINESSSCOPE = BUSINESSSCOPE == null ? null : BUSINESSSCOPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.FAX
     *
     * @return the value of DRUGSTORE.FAX
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getFAX() {
        return FAX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.FAX
     *
     * @param FAX the value for DRUGSTORE.FAX
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setFAX(String FAX) {
        this.FAX = FAX == null ? null : FAX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.VIDEOURL
     *
     * @return the value of DRUGSTORE.VIDEOURL
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getVIDEOURL() {
        return VIDEOURL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.VIDEOURL
     *
     * @param VIDEOURL the value for DRUGSTORE.VIDEOURL
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setVIDEOURL(String VIDEOURL) {
        this.VIDEOURL = VIDEOURL == null ? null : VIDEOURL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.ISSUPERVISED
     *
     * @return the value of DRUGSTORE.ISSUPERVISED
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public BigDecimal getISSUPERVISED() {
        return ISSUPERVISED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.ISSUPERVISED
     *
     * @param ISSUPERVISED the value for DRUGSTORE.ISSUPERVISED
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setISSUPERVISED(BigDecimal ISSUPERVISED) {
        this.ISSUPERVISED = ISSUPERVISED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.REMARK
     *
     * @return the value of DRUGSTORE.REMARK
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getREMARK() {
        return REMARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.REMARK
     *
     * @param REMARK the value for DRUGSTORE.REMARK
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setREMARK(String REMARK) {
        this.REMARK = REMARK == null ? null : REMARK.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.LASTGRADEDATE
     *
     * @return the value of DRUGSTORE.LASTGRADEDATE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public Date getLASTGRADEDATE() {
        return LASTGRADEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.LASTGRADEDATE
     *
     * @param LASTGRADEDATE the value for DRUGSTORE.LASTGRADEDATE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setLASTGRADEDATE(Date LASTGRADEDATE) {
        this.LASTGRADEDATE = LASTGRADEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.NATURE
     *
     * @return the value of DRUGSTORE.NATURE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getNATURE() {
        return NATURE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.NATURE
     *
     * @param NATURE the value for DRUGSTORE.NATURE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setNATURE(String NATURE) {
        this.NATURE = NATURE == null ? null : NATURE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.PEOPLECOUNT
     *
     * @return the value of DRUGSTORE.PEOPLECOUNT
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public BigDecimal getPEOPLECOUNT() {
        return PEOPLECOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.PEOPLECOUNT
     *
     * @param PEOPLECOUNT the value for DRUGSTORE.PEOPLECOUNT
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setPEOPLECOUNT(BigDecimal PEOPLECOUNT) {
        this.PEOPLECOUNT = PEOPLECOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.RJOBTITLE
     *
     * @return the value of DRUGSTORE.RJOBTITLE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getRJOBTITLE() {
        return RJOBTITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.RJOBTITLE
     *
     * @param RJOBTITLE the value for DRUGSTORE.RJOBTITLE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setRJOBTITLE(String RJOBTITLE) {
        this.RJOBTITLE = RJOBTITLE == null ? null : RJOBTITLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.RPHONENO
     *
     * @return the value of DRUGSTORE.RPHONENO
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getRPHONENO() {
        return RPHONENO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.RPHONENO
     *
     * @param RPHONENO the value for DRUGSTORE.RPHONENO
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setRPHONENO(String RPHONENO) {
        this.RPHONENO = RPHONENO == null ? null : RPHONENO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.RPOST
     *
     * @return the value of DRUGSTORE.RPOST
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getRPOST() {
        return RPOST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.RPOST
     *
     * @param RPOST the value for DRUGSTORE.RPOST
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setRPOST(String RPOST) {
        this.RPOST = RPOST == null ? null : RPOST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.LEGALPERSON
     *
     * @return the value of DRUGSTORE.LEGALPERSON
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getLEGALPERSON() {
        return LEGALPERSON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.LEGALPERSON
     *
     * @param LEGALPERSON the value for DRUGSTORE.LEGALPERSON
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setLEGALPERSON(String LEGALPERSON) {
        this.LEGALPERSON = LEGALPERSON == null ? null : LEGALPERSON.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.LJOBTITLE
     *
     * @return the value of DRUGSTORE.LJOBTITLE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getLJOBTITLE() {
        return LJOBTITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.LJOBTITLE
     *
     * @param LJOBTITLE the value for DRUGSTORE.LJOBTITLE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setLJOBTITLE(String LJOBTITLE) {
        this.LJOBTITLE = LJOBTITLE == null ? null : LJOBTITLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.LPHONENO
     *
     * @return the value of DRUGSTORE.LPHONENO
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getLPHONENO() {
        return LPHONENO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.LPHONENO
     *
     * @param LPHONENO the value for DRUGSTORE.LPHONENO
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setLPHONENO(String LPHONENO) {
        this.LPHONENO = LPHONENO == null ? null : LPHONENO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.LPOST
     *
     * @return the value of DRUGSTORE.LPOST
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getLPOST() {
        return LPOST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.LPOST
     *
     * @param LPOST the value for DRUGSTORE.LPOST
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setLPOST(String LPOST) {
        this.LPOST = LPOST == null ? null : LPOST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.QUALITYPERSON
     *
     * @return the value of DRUGSTORE.QUALITYPERSON
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getQUALITYPERSON() {
        return QUALITYPERSON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.QUALITYPERSON
     *
     * @param QUALITYPERSON the value for DRUGSTORE.QUALITYPERSON
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setQUALITYPERSON(String QUALITYPERSON) {
        this.QUALITYPERSON = QUALITYPERSON == null ? null : QUALITYPERSON.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.QJOBTITLE
     *
     * @return the value of DRUGSTORE.QJOBTITLE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getQJOBTITLE() {
        return QJOBTITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.QJOBTITLE
     *
     * @param QJOBTITLE the value for DRUGSTORE.QJOBTITLE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setQJOBTITLE(String QJOBTITLE) {
        this.QJOBTITLE = QJOBTITLE == null ? null : QJOBTITLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.QPHONENO
     *
     * @return the value of DRUGSTORE.QPHONENO
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getQPHONENO() {
        return QPHONENO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.QPHONENO
     *
     * @param QPHONENO the value for DRUGSTORE.QPHONENO
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setQPHONENO(String QPHONENO) {
        this.QPHONENO = QPHONENO == null ? null : QPHONENO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.QPOST
     *
     * @return the value of DRUGSTORE.QPOST
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getQPOST() {
        return QPOST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.QPOST
     *
     * @param QPOST the value for DRUGSTORE.QPOST
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setQPOST(String QPOST) {
        this.QPOST = QPOST == null ? null : QPOST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.DRUGCHECKPERSON
     *
     * @return the value of DRUGSTORE.DRUGCHECKPERSON
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getDRUGCHECKPERSON() {
        return DRUGCHECKPERSON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.DRUGCHECKPERSON
     *
     * @param DRUGCHECKPERSON the value for DRUGSTORE.DRUGCHECKPERSON
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setDRUGCHECKPERSON(String DRUGCHECKPERSON) {
        this.DRUGCHECKPERSON = DRUGCHECKPERSON == null ? null : DRUGCHECKPERSON.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.DJOBTITLE
     *
     * @return the value of DRUGSTORE.DJOBTITLE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getDJOBTITLE() {
        return DJOBTITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.DJOBTITLE
     *
     * @param DJOBTITLE the value for DRUGSTORE.DJOBTITLE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setDJOBTITLE(String DJOBTITLE) {
        this.DJOBTITLE = DJOBTITLE == null ? null : DJOBTITLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.DPHONENO
     *
     * @return the value of DRUGSTORE.DPHONENO
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getDPHONENO() {
        return DPHONENO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.DPHONENO
     *
     * @param DPHONENO the value for DRUGSTORE.DPHONENO
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setDPHONENO(String DPHONENO) {
        this.DPHONENO = DPHONENO == null ? null : DPHONENO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.DPOST
     *
     * @return the value of DRUGSTORE.DPOST
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getDPOST() {
        return DPOST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.DPOST
     *
     * @param DPOST the value for DRUGSTORE.DPOST
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setDPOST(String DPOST) {
        this.DPOST = DPOST == null ? null : DPOST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRUGSTORE.OTHERPEOPLE
     *
     * @return the value of DRUGSTORE.OTHERPEOPLE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public String getOTHERPEOPLE() {
        return OTHERPEOPLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRUGSTORE.OTHERPEOPLE
     *
     * @param OTHERPEOPLE the value for DRUGSTORE.OTHERPEOPLE
     *
     * @mbggenerated Wed Jan 16 09:15:22 CST 2013
     */
    public void setOTHERPEOPLE(String OTHERPEOPLE) {
        this.OTHERPEOPLE = OTHERPEOPLE == null ? null : OTHERPEOPLE.trim();
    }
}