package com.wildwolf.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PharmacistExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PHARMACIST
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PHARMACIST
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PHARMACIST
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHARMACIST
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public PharmacistExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHARMACIST
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    protected PharmacistExample(PharmacistExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.distinct = example.distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHARMACIST
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHARMACIST
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHARMACIST
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHARMACIST
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHARMACIST
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHARMACIST
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHARMACIST
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHARMACIST
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHARMACIST
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHARMACIST
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PHARMACIST
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected GeneratedCriteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andUSERIDIsNull() {
            addCriterion("USERID is null");
            return (Criteria) this;
        }

        public Criteria andUSERIDIsNotNull() {
            addCriterion("USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUSERIDEqualTo(String value) {
            addCriterion("USERID =", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDNotEqualTo(String value) {
            addCriterion("USERID <>", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDGreaterThan(String value) {
            addCriterion("USERID >", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDGreaterThanOrEqualTo(String value) {
            addCriterion("USERID >=", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDLessThan(String value) {
            addCriterion("USERID <", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDLessThanOrEqualTo(String value) {
            addCriterion("USERID <=", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDLike(String value) {
            addCriterion("USERID like", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDNotLike(String value) {
            addCriterion("USERID not like", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDIn(List values) {
            addCriterion("USERID in", values, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDNotIn(List values) {
            addCriterion("USERID not in", values, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDBetween(String value1, String value2) {
            addCriterion("USERID between", value1, value2, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDNotBetween(String value1, String value2) {
            addCriterion("USERID not between", value1, value2, "USERID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDIsNull() {
            addCriterion("DRUGSTOREID is null");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDIsNotNull() {
            addCriterion("DRUGSTOREID is not null");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDEqualTo(String value) {
            addCriterion("DRUGSTOREID =", value, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDNotEqualTo(String value) {
            addCriterion("DRUGSTOREID <>", value, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDGreaterThan(String value) {
            addCriterion("DRUGSTOREID >", value, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDGreaterThanOrEqualTo(String value) {
            addCriterion("DRUGSTOREID >=", value, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDLessThan(String value) {
            addCriterion("DRUGSTOREID <", value, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDLessThanOrEqualTo(String value) {
            addCriterion("DRUGSTOREID <=", value, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDLike(String value) {
            addCriterion("DRUGSTOREID like", value, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDNotLike(String value) {
            addCriterion("DRUGSTOREID not like", value, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDIn(List values) {
            addCriterion("DRUGSTOREID in", values, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDNotIn(List values) {
            addCriterion("DRUGSTOREID not in", values, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDBetween(String value1, String value2) {
            addCriterion("DRUGSTOREID between", value1, value2, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andDRUGSTOREIDNotBetween(String value1, String value2) {
            addCriterion("DRUGSTOREID not between", value1, value2, "DRUGSTOREID");
            return (Criteria) this;
        }

        public Criteria andPHNAMEIsNull() {
            addCriterion("PHNAME is null");
            return (Criteria) this;
        }

        public Criteria andPHNAMEIsNotNull() {
            addCriterion("PHNAME is not null");
            return (Criteria) this;
        }

        public Criteria andPHNAMEEqualTo(String value) {
            addCriterion("PHNAME =", value, "PHNAME");
            return (Criteria) this;
        }

        public Criteria andPHNAMENotEqualTo(String value) {
            addCriterion("PHNAME <>", value, "PHNAME");
            return (Criteria) this;
        }

        public Criteria andPHNAMEGreaterThan(String value) {
            addCriterion("PHNAME >", value, "PHNAME");
            return (Criteria) this;
        }

        public Criteria andPHNAMEGreaterThanOrEqualTo(String value) {
            addCriterion("PHNAME >=", value, "PHNAME");
            return (Criteria) this;
        }

        public Criteria andPHNAMELessThan(String value) {
            addCriterion("PHNAME <", value, "PHNAME");
            return (Criteria) this;
        }

        public Criteria andPHNAMELessThanOrEqualTo(String value) {
            addCriterion("PHNAME <=", value, "PHNAME");
            return (Criteria) this;
        }

        public Criteria andPHNAMELike(String value) {
            addCriterion("PHNAME like", value, "PHNAME");
            return (Criteria) this;
        }

        public Criteria andPHNAMENotLike(String value) {
            addCriterion("PHNAME not like", value, "PHNAME");
            return (Criteria) this;
        }

        public Criteria andPHNAMEIn(List values) {
            addCriterion("PHNAME in", values, "PHNAME");
            return (Criteria) this;
        }

        public Criteria andPHNAMENotIn(List values) {
            addCriterion("PHNAME not in", values, "PHNAME");
            return (Criteria) this;
        }

        public Criteria andPHNAMEBetween(String value1, String value2) {
            addCriterion("PHNAME between", value1, value2, "PHNAME");
            return (Criteria) this;
        }

        public Criteria andPHNAMENotBetween(String value1, String value2) {
            addCriterion("PHNAME not between", value1, value2, "PHNAME");
            return (Criteria) this;
        }

        public Criteria andTELIsNull() {
            addCriterion("TEL is null");
            return (Criteria) this;
        }

        public Criteria andTELIsNotNull() {
            addCriterion("TEL is not null");
            return (Criteria) this;
        }

        public Criteria andTELEqualTo(String value) {
            addCriterion("TEL =", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELNotEqualTo(String value) {
            addCriterion("TEL <>", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELGreaterThan(String value) {
            addCriterion("TEL >", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELGreaterThanOrEqualTo(String value) {
            addCriterion("TEL >=", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELLessThan(String value) {
            addCriterion("TEL <", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELLessThanOrEqualTo(String value) {
            addCriterion("TEL <=", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELLike(String value) {
            addCriterion("TEL like", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELNotLike(String value) {
            addCriterion("TEL not like", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELIn(List values) {
            addCriterion("TEL in", values, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELNotIn(List values) {
            addCriterion("TEL not in", values, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELBetween(String value1, String value2) {
            addCriterion("TEL between", value1, value2, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELNotBetween(String value1, String value2) {
            addCriterion("TEL not between", value1, value2, "TEL");
            return (Criteria) this;
        }

        public Criteria andADDRESSIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andADDRESSIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andADDRESSEqualTo(String value) {
            addCriterion("ADDRESS =", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSLessThan(String value) {
            addCriterion("ADDRESS <", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSLike(String value) {
            addCriterion("ADDRESS like", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSNotLike(String value) {
            addCriterion("ADDRESS not like", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSIn(List values) {
            addCriterion("ADDRESS in", values, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSNotIn(List values) {
            addCriterion("ADDRESS not in", values, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andAGEIsNull() {
            addCriterion("AGE is null");
            return (Criteria) this;
        }

        public Criteria andAGEIsNotNull() {
            addCriterion("AGE is not null");
            return (Criteria) this;
        }

        public Criteria andAGEEqualTo(BigDecimal value) {
            addCriterion("AGE =", value, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGENotEqualTo(BigDecimal value) {
            addCriterion("AGE <>", value, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGEGreaterThan(BigDecimal value) {
            addCriterion("AGE >", value, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGEGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AGE >=", value, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGELessThan(BigDecimal value) {
            addCriterion("AGE <", value, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGELessThanOrEqualTo(BigDecimal value) {
            addCriterion("AGE <=", value, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGEIn(List values) {
            addCriterion("AGE in", values, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGENotIn(List values) {
            addCriterion("AGE not in", values, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGEBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AGE between", value1, value2, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGENotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AGE not between", value1, value2, "AGE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATEIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCREATEDATEIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCREATEDATEEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATENotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATEGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATEGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATELessThan(Date value) {
            addCriterion("CREATEDATE <", value, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATELessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATEIn(List values) {
            addCriterion("CREATEDATE in", values, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATENotIn(List values) {
            addCriterion("CREATEDATE not in", values, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATEBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andCREATEDATENotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "CREATEDATE");
            return (Criteria) this;
        }

        public Criteria andUPDATEDATEIsNull() {
            addCriterion("UPDATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andUPDATEDATEIsNotNull() {
            addCriterion("UPDATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andUPDATEDATEEqualTo(Date value) {
            addCriterion("UPDATEDATE =", value, "UPDATEDATE");
            return (Criteria) this;
        }

        public Criteria andUPDATEDATENotEqualTo(Date value) {
            addCriterion("UPDATEDATE <>", value, "UPDATEDATE");
            return (Criteria) this;
        }

        public Criteria andUPDATEDATEGreaterThan(Date value) {
            addCriterion("UPDATEDATE >", value, "UPDATEDATE");
            return (Criteria) this;
        }

        public Criteria andUPDATEDATEGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATEDATE >=", value, "UPDATEDATE");
            return (Criteria) this;
        }

        public Criteria andUPDATEDATELessThan(Date value) {
            addCriterion("UPDATEDATE <", value, "UPDATEDATE");
            return (Criteria) this;
        }

        public Criteria andUPDATEDATELessThanOrEqualTo(Date value) {
            addCriterion("UPDATEDATE <=", value, "UPDATEDATE");
            return (Criteria) this;
        }

        public Criteria andUPDATEDATEIn(List values) {
            addCriterion("UPDATEDATE in", values, "UPDATEDATE");
            return (Criteria) this;
        }

        public Criteria andUPDATEDATENotIn(List values) {
            addCriterion("UPDATEDATE not in", values, "UPDATEDATE");
            return (Criteria) this;
        }

        public Criteria andUPDATEDATEBetween(Date value1, Date value2) {
            addCriterion("UPDATEDATE between", value1, value2, "UPDATEDATE");
            return (Criteria) this;
        }

        public Criteria andUPDATEDATENotBetween(Date value1, Date value2) {
            addCriterion("UPDATEDATE not between", value1, value2, "UPDATEDATE");
            return (Criteria) this;
        }

        public Criteria andFINGERPRINTIsNull() {
            addCriterion("FINGERPRINT is null");
            return (Criteria) this;
        }

        public Criteria andFINGERPRINTIsNotNull() {
            addCriterion("FINGERPRINT is not null");
            return (Criteria) this;
        }

        public Criteria andFINGERPRINTEqualTo(String value) {
            addCriterion("FINGERPRINT =", value, "FINGERPRINT");
            return (Criteria) this;
        }

        public Criteria andFINGERPRINTNotEqualTo(String value) {
            addCriterion("FINGERPRINT <>", value, "FINGERPRINT");
            return (Criteria) this;
        }

        public Criteria andFINGERPRINTGreaterThan(String value) {
            addCriterion("FINGERPRINT >", value, "FINGERPRINT");
            return (Criteria) this;
        }

        public Criteria andFINGERPRINTGreaterThanOrEqualTo(String value) {
            addCriterion("FINGERPRINT >=", value, "FINGERPRINT");
            return (Criteria) this;
        }

        public Criteria andFINGERPRINTLessThan(String value) {
            addCriterion("FINGERPRINT <", value, "FINGERPRINT");
            return (Criteria) this;
        }

        public Criteria andFINGERPRINTLessThanOrEqualTo(String value) {
            addCriterion("FINGERPRINT <=", value, "FINGERPRINT");
            return (Criteria) this;
        }

        public Criteria andFINGERPRINTLike(String value) {
            addCriterion("FINGERPRINT like", value, "FINGERPRINT");
            return (Criteria) this;
        }

        public Criteria andFINGERPRINTNotLike(String value) {
            addCriterion("FINGERPRINT not like", value, "FINGERPRINT");
            return (Criteria) this;
        }

        public Criteria andFINGERPRINTIn(List values) {
            addCriterion("FINGERPRINT in", values, "FINGERPRINT");
            return (Criteria) this;
        }

        public Criteria andFINGERPRINTNotIn(List values) {
            addCriterion("FINGERPRINT not in", values, "FINGERPRINT");
            return (Criteria) this;
        }

        public Criteria andFINGERPRINTBetween(String value1, String value2) {
            addCriterion("FINGERPRINT between", value1, value2, "FINGERPRINT");
            return (Criteria) this;
        }

        public Criteria andFINGERPRINTNotBetween(String value1, String value2) {
            addCriterion("FINGERPRINT not between", value1, value2, "FINGERPRINT");
            return (Criteria) this;
        }

        public Criteria andSEXIsNull() {
            addCriterion("SEX is null");
            return (Criteria) this;
        }

        public Criteria andSEXIsNotNull() {
            addCriterion("SEX is not null");
            return (Criteria) this;
        }

        public Criteria andSEXEqualTo(BigDecimal value) {
            addCriterion("SEX =", value, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXNotEqualTo(BigDecimal value) {
            addCriterion("SEX <>", value, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXGreaterThan(BigDecimal value) {
            addCriterion("SEX >", value, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SEX >=", value, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXLessThan(BigDecimal value) {
            addCriterion("SEX <", value, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SEX <=", value, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXIn(List values) {
            addCriterion("SEX in", values, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXNotIn(List values) {
            addCriterion("SEX not in", values, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SEX between", value1, value2, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SEX not between", value1, value2, "SEX");
            return (Criteria) this;
        }

        public Criteria andCERTIFICATEIDIsNull() {
            addCriterion("CERTIFICATEID is null");
            return (Criteria) this;
        }

        public Criteria andCERTIFICATEIDIsNotNull() {
            addCriterion("CERTIFICATEID is not null");
            return (Criteria) this;
        }

        public Criteria andCERTIFICATEIDEqualTo(String value) {
            addCriterion("CERTIFICATEID =", value, "CERTIFICATEID");
            return (Criteria) this;
        }

        public Criteria andCERTIFICATEIDNotEqualTo(String value) {
            addCriterion("CERTIFICATEID <>", value, "CERTIFICATEID");
            return (Criteria) this;
        }

        public Criteria andCERTIFICATEIDGreaterThan(String value) {
            addCriterion("CERTIFICATEID >", value, "CERTIFICATEID");
            return (Criteria) this;
        }

        public Criteria andCERTIFICATEIDGreaterThanOrEqualTo(String value) {
            addCriterion("CERTIFICATEID >=", value, "CERTIFICATEID");
            return (Criteria) this;
        }

        public Criteria andCERTIFICATEIDLessThan(String value) {
            addCriterion("CERTIFICATEID <", value, "CERTIFICATEID");
            return (Criteria) this;
        }

        public Criteria andCERTIFICATEIDLessThanOrEqualTo(String value) {
            addCriterion("CERTIFICATEID <=", value, "CERTIFICATEID");
            return (Criteria) this;
        }

        public Criteria andCERTIFICATEIDLike(String value) {
            addCriterion("CERTIFICATEID like", value, "CERTIFICATEID");
            return (Criteria) this;
        }

        public Criteria andCERTIFICATEIDNotLike(String value) {
            addCriterion("CERTIFICATEID not like", value, "CERTIFICATEID");
            return (Criteria) this;
        }

        public Criteria andCERTIFICATEIDIn(List values) {
            addCriterion("CERTIFICATEID in", values, "CERTIFICATEID");
            return (Criteria) this;
        }

        public Criteria andCERTIFICATEIDNotIn(List values) {
            addCriterion("CERTIFICATEID not in", values, "CERTIFICATEID");
            return (Criteria) this;
        }

        public Criteria andCERTIFICATEIDBetween(String value1, String value2) {
            addCriterion("CERTIFICATEID between", value1, value2, "CERTIFICATEID");
            return (Criteria) this;
        }

        public Criteria andCERTIFICATEIDNotBetween(String value1, String value2) {
            addCriterion("CERTIFICATEID not between", value1, value2, "CERTIFICATEID");
            return (Criteria) this;
        }

        public Criteria andNATIVEPLACEIsNull() {
            addCriterion("NATIVEPLACE is null");
            return (Criteria) this;
        }

        public Criteria andNATIVEPLACEIsNotNull() {
            addCriterion("NATIVEPLACE is not null");
            return (Criteria) this;
        }

        public Criteria andNATIVEPLACEEqualTo(String value) {
            addCriterion("NATIVEPLACE =", value, "NATIVEPLACE");
            return (Criteria) this;
        }

        public Criteria andNATIVEPLACENotEqualTo(String value) {
            addCriterion("NATIVEPLACE <>", value, "NATIVEPLACE");
            return (Criteria) this;
        }

        public Criteria andNATIVEPLACEGreaterThan(String value) {
            addCriterion("NATIVEPLACE >", value, "NATIVEPLACE");
            return (Criteria) this;
        }

        public Criteria andNATIVEPLACEGreaterThanOrEqualTo(String value) {
            addCriterion("NATIVEPLACE >=", value, "NATIVEPLACE");
            return (Criteria) this;
        }

        public Criteria andNATIVEPLACELessThan(String value) {
            addCriterion("NATIVEPLACE <", value, "NATIVEPLACE");
            return (Criteria) this;
        }

        public Criteria andNATIVEPLACELessThanOrEqualTo(String value) {
            addCriterion("NATIVEPLACE <=", value, "NATIVEPLACE");
            return (Criteria) this;
        }

        public Criteria andNATIVEPLACELike(String value) {
            addCriterion("NATIVEPLACE like", value, "NATIVEPLACE");
            return (Criteria) this;
        }

        public Criteria andNATIVEPLACENotLike(String value) {
            addCriterion("NATIVEPLACE not like", value, "NATIVEPLACE");
            return (Criteria) this;
        }

        public Criteria andNATIVEPLACEIn(List values) {
            addCriterion("NATIVEPLACE in", values, "NATIVEPLACE");
            return (Criteria) this;
        }

        public Criteria andNATIVEPLACENotIn(List values) {
            addCriterion("NATIVEPLACE not in", values, "NATIVEPLACE");
            return (Criteria) this;
        }

        public Criteria andNATIVEPLACEBetween(String value1, String value2) {
            addCriterion("NATIVEPLACE between", value1, value2, "NATIVEPLACE");
            return (Criteria) this;
        }

        public Criteria andNATIVEPLACENotBetween(String value1, String value2) {
            addCriterion("NATIVEPLACE not between", value1, value2, "NATIVEPLACE");
            return (Criteria) this;
        }

        public Criteria andPOSITIONIsNull() {
            addCriterion("POSITION is null");
            return (Criteria) this;
        }

        public Criteria andPOSITIONIsNotNull() {
            addCriterion("POSITION is not null");
            return (Criteria) this;
        }

        public Criteria andPOSITIONEqualTo(String value) {
            addCriterion("POSITION =", value, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONNotEqualTo(String value) {
            addCriterion("POSITION <>", value, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONGreaterThan(String value) {
            addCriterion("POSITION >", value, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONGreaterThanOrEqualTo(String value) {
            addCriterion("POSITION >=", value, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONLessThan(String value) {
            addCriterion("POSITION <", value, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONLessThanOrEqualTo(String value) {
            addCriterion("POSITION <=", value, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONLike(String value) {
            addCriterion("POSITION like", value, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONNotLike(String value) {
            addCriterion("POSITION not like", value, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONIn(List values) {
            addCriterion("POSITION in", values, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONNotIn(List values) {
            addCriterion("POSITION not in", values, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONBetween(String value1, String value2) {
            addCriterion("POSITION between", value1, value2, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONNotBetween(String value1, String value2) {
            addCriterion("POSITION not between", value1, value2, "POSITION");
            return (Criteria) this;
        }

        public Criteria andEDUCATIONIsNull() {
            addCriterion("EDUCATION is null");
            return (Criteria) this;
        }

        public Criteria andEDUCATIONIsNotNull() {
            addCriterion("EDUCATION is not null");
            return (Criteria) this;
        }

        public Criteria andEDUCATIONEqualTo(String value) {
            addCriterion("EDUCATION =", value, "EDUCATION");
            return (Criteria) this;
        }

        public Criteria andEDUCATIONNotEqualTo(String value) {
            addCriterion("EDUCATION <>", value, "EDUCATION");
            return (Criteria) this;
        }

        public Criteria andEDUCATIONGreaterThan(String value) {
            addCriterion("EDUCATION >", value, "EDUCATION");
            return (Criteria) this;
        }

        public Criteria andEDUCATIONGreaterThanOrEqualTo(String value) {
            addCriterion("EDUCATION >=", value, "EDUCATION");
            return (Criteria) this;
        }

        public Criteria andEDUCATIONLessThan(String value) {
            addCriterion("EDUCATION <", value, "EDUCATION");
            return (Criteria) this;
        }

        public Criteria andEDUCATIONLessThanOrEqualTo(String value) {
            addCriterion("EDUCATION <=", value, "EDUCATION");
            return (Criteria) this;
        }

        public Criteria andEDUCATIONLike(String value) {
            addCriterion("EDUCATION like", value, "EDUCATION");
            return (Criteria) this;
        }

        public Criteria andEDUCATIONNotLike(String value) {
            addCriterion("EDUCATION not like", value, "EDUCATION");
            return (Criteria) this;
        }

        public Criteria andEDUCATIONIn(List values) {
            addCriterion("EDUCATION in", values, "EDUCATION");
            return (Criteria) this;
        }

        public Criteria andEDUCATIONNotIn(List values) {
            addCriterion("EDUCATION not in", values, "EDUCATION");
            return (Criteria) this;
        }

        public Criteria andEDUCATIONBetween(String value1, String value2) {
            addCriterion("EDUCATION between", value1, value2, "EDUCATION");
            return (Criteria) this;
        }

        public Criteria andEDUCATIONNotBetween(String value1, String value2) {
            addCriterion("EDUCATION not between", value1, value2, "EDUCATION");
            return (Criteria) this;
        }

        public Criteria andGRADUATEIsNull() {
            addCriterion("GRADUATE is null");
            return (Criteria) this;
        }

        public Criteria andGRADUATEIsNotNull() {
            addCriterion("GRADUATE is not null");
            return (Criteria) this;
        }

        public Criteria andGRADUATEEqualTo(String value) {
            addCriterion("GRADUATE =", value, "GRADUATE");
            return (Criteria) this;
        }

        public Criteria andGRADUATENotEqualTo(String value) {
            addCriterion("GRADUATE <>", value, "GRADUATE");
            return (Criteria) this;
        }

        public Criteria andGRADUATEGreaterThan(String value) {
            addCriterion("GRADUATE >", value, "GRADUATE");
            return (Criteria) this;
        }

        public Criteria andGRADUATEGreaterThanOrEqualTo(String value) {
            addCriterion("GRADUATE >=", value, "GRADUATE");
            return (Criteria) this;
        }

        public Criteria andGRADUATELessThan(String value) {
            addCriterion("GRADUATE <", value, "GRADUATE");
            return (Criteria) this;
        }

        public Criteria andGRADUATELessThanOrEqualTo(String value) {
            addCriterion("GRADUATE <=", value, "GRADUATE");
            return (Criteria) this;
        }

        public Criteria andGRADUATELike(String value) {
            addCriterion("GRADUATE like", value, "GRADUATE");
            return (Criteria) this;
        }

        public Criteria andGRADUATENotLike(String value) {
            addCriterion("GRADUATE not like", value, "GRADUATE");
            return (Criteria) this;
        }

        public Criteria andGRADUATEIn(List values) {
            addCriterion("GRADUATE in", values, "GRADUATE");
            return (Criteria) this;
        }

        public Criteria andGRADUATENotIn(List values) {
            addCriterion("GRADUATE not in", values, "GRADUATE");
            return (Criteria) this;
        }

        public Criteria andGRADUATEBetween(String value1, String value2) {
            addCriterion("GRADUATE between", value1, value2, "GRADUATE");
            return (Criteria) this;
        }

        public Criteria andGRADUATENotBetween(String value1, String value2) {
            addCriterion("GRADUATE not between", value1, value2, "GRADUATE");
            return (Criteria) this;
        }

        public Criteria andIDCARDNOIsNull() {
            addCriterion("IDCARDNO is null");
            return (Criteria) this;
        }

        public Criteria andIDCARDNOIsNotNull() {
            addCriterion("IDCARDNO is not null");
            return (Criteria) this;
        }

        public Criteria andIDCARDNOEqualTo(String value) {
            addCriterion("IDCARDNO =", value, "IDCARDNO");
            return (Criteria) this;
        }

        public Criteria andIDCARDNONotEqualTo(String value) {
            addCriterion("IDCARDNO <>", value, "IDCARDNO");
            return (Criteria) this;
        }

        public Criteria andIDCARDNOGreaterThan(String value) {
            addCriterion("IDCARDNO >", value, "IDCARDNO");
            return (Criteria) this;
        }

        public Criteria andIDCARDNOGreaterThanOrEqualTo(String value) {
            addCriterion("IDCARDNO >=", value, "IDCARDNO");
            return (Criteria) this;
        }

        public Criteria andIDCARDNOLessThan(String value) {
            addCriterion("IDCARDNO <", value, "IDCARDNO");
            return (Criteria) this;
        }

        public Criteria andIDCARDNOLessThanOrEqualTo(String value) {
            addCriterion("IDCARDNO <=", value, "IDCARDNO");
            return (Criteria) this;
        }

        public Criteria andIDCARDNOLike(String value) {
            addCriterion("IDCARDNO like", value, "IDCARDNO");
            return (Criteria) this;
        }

        public Criteria andIDCARDNONotLike(String value) {
            addCriterion("IDCARDNO not like", value, "IDCARDNO");
            return (Criteria) this;
        }

        public Criteria andIDCARDNOIn(List values) {
            addCriterion("IDCARDNO in", values, "IDCARDNO");
            return (Criteria) this;
        }

        public Criteria andIDCARDNONotIn(List values) {
            addCriterion("IDCARDNO not in", values, "IDCARDNO");
            return (Criteria) this;
        }

        public Criteria andIDCARDNOBetween(String value1, String value2) {
            addCriterion("IDCARDNO between", value1, value2, "IDCARDNO");
            return (Criteria) this;
        }

        public Criteria andIDCARDNONotBetween(String value1, String value2) {
            addCriterion("IDCARDNO not between", value1, value2, "IDCARDNO");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYIsNull() {
            addCriterion("BIRTHDAY is null");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYIsNotNull() {
            addCriterion("BIRTHDAY is not null");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYEqualTo(Date value) {
            addCriterion("BIRTHDAY =", value, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYNotEqualTo(Date value) {
            addCriterion("BIRTHDAY <>", value, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYGreaterThan(Date value) {
            addCriterion("BIRTHDAY >", value, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYGreaterThanOrEqualTo(Date value) {
            addCriterion("BIRTHDAY >=", value, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYLessThan(Date value) {
            addCriterion("BIRTHDAY <", value, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYLessThanOrEqualTo(Date value) {
            addCriterion("BIRTHDAY <=", value, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYIn(List values) {
            addCriterion("BIRTHDAY in", values, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYNotIn(List values) {
            addCriterion("BIRTHDAY not in", values, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYBetween(Date value1, Date value2) {
            addCriterion("BIRTHDAY between", value1, value2, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYNotBetween(Date value1, Date value2) {
            addCriterion("BIRTHDAY not between", value1, value2, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andQUALIFICATIONIsNull() {
            addCriterion("QUALIFICATION is null");
            return (Criteria) this;
        }

        public Criteria andQUALIFICATIONIsNotNull() {
            addCriterion("QUALIFICATION is not null");
            return (Criteria) this;
        }

        public Criteria andQUALIFICATIONEqualTo(String value) {
            addCriterion("QUALIFICATION =", value, "QUALIFICATION");
            return (Criteria) this;
        }

        public Criteria andQUALIFICATIONNotEqualTo(String value) {
            addCriterion("QUALIFICATION <>", value, "QUALIFICATION");
            return (Criteria) this;
        }

        public Criteria andQUALIFICATIONGreaterThan(String value) {
            addCriterion("QUALIFICATION >", value, "QUALIFICATION");
            return (Criteria) this;
        }

        public Criteria andQUALIFICATIONGreaterThanOrEqualTo(String value) {
            addCriterion("QUALIFICATION >=", value, "QUALIFICATION");
            return (Criteria) this;
        }

        public Criteria andQUALIFICATIONLessThan(String value) {
            addCriterion("QUALIFICATION <", value, "QUALIFICATION");
            return (Criteria) this;
        }

        public Criteria andQUALIFICATIONLessThanOrEqualTo(String value) {
            addCriterion("QUALIFICATION <=", value, "QUALIFICATION");
            return (Criteria) this;
        }

        public Criteria andQUALIFICATIONLike(String value) {
            addCriterion("QUALIFICATION like", value, "QUALIFICATION");
            return (Criteria) this;
        }

        public Criteria andQUALIFICATIONNotLike(String value) {
            addCriterion("QUALIFICATION not like", value, "QUALIFICATION");
            return (Criteria) this;
        }

        public Criteria andQUALIFICATIONIn(List values) {
            addCriterion("QUALIFICATION in", values, "QUALIFICATION");
            return (Criteria) this;
        }

        public Criteria andQUALIFICATIONNotIn(List values) {
            addCriterion("QUALIFICATION not in", values, "QUALIFICATION");
            return (Criteria) this;
        }

        public Criteria andQUALIFICATIONBetween(String value1, String value2) {
            addCriterion("QUALIFICATION between", value1, value2, "QUALIFICATION");
            return (Criteria) this;
        }

        public Criteria andQUALIFICATIONNotBetween(String value1, String value2) {
            addCriterion("QUALIFICATION not between", value1, value2, "QUALIFICATION");
            return (Criteria) this;
        }

        public Criteria andLSSUEUNITIsNull() {
            addCriterion("LSSUEUNIT is null");
            return (Criteria) this;
        }

        public Criteria andLSSUEUNITIsNotNull() {
            addCriterion("LSSUEUNIT is not null");
            return (Criteria) this;
        }

        public Criteria andLSSUEUNITEqualTo(String value) {
            addCriterion("LSSUEUNIT =", value, "LSSUEUNIT");
            return (Criteria) this;
        }

        public Criteria andLSSUEUNITNotEqualTo(String value) {
            addCriterion("LSSUEUNIT <>", value, "LSSUEUNIT");
            return (Criteria) this;
        }

        public Criteria andLSSUEUNITGreaterThan(String value) {
            addCriterion("LSSUEUNIT >", value, "LSSUEUNIT");
            return (Criteria) this;
        }

        public Criteria andLSSUEUNITGreaterThanOrEqualTo(String value) {
            addCriterion("LSSUEUNIT >=", value, "LSSUEUNIT");
            return (Criteria) this;
        }

        public Criteria andLSSUEUNITLessThan(String value) {
            addCriterion("LSSUEUNIT <", value, "LSSUEUNIT");
            return (Criteria) this;
        }

        public Criteria andLSSUEUNITLessThanOrEqualTo(String value) {
            addCriterion("LSSUEUNIT <=", value, "LSSUEUNIT");
            return (Criteria) this;
        }

        public Criteria andLSSUEUNITLike(String value) {
            addCriterion("LSSUEUNIT like", value, "LSSUEUNIT");
            return (Criteria) this;
        }

        public Criteria andLSSUEUNITNotLike(String value) {
            addCriterion("LSSUEUNIT not like", value, "LSSUEUNIT");
            return (Criteria) this;
        }

        public Criteria andLSSUEUNITIn(List values) {
            addCriterion("LSSUEUNIT in", values, "LSSUEUNIT");
            return (Criteria) this;
        }

        public Criteria andLSSUEUNITNotIn(List values) {
            addCriterion("LSSUEUNIT not in", values, "LSSUEUNIT");
            return (Criteria) this;
        }

        public Criteria andLSSUEUNITBetween(String value1, String value2) {
            addCriterion("LSSUEUNIT between", value1, value2, "LSSUEUNIT");
            return (Criteria) this;
        }

        public Criteria andLSSUEUNITNotBetween(String value1, String value2) {
            addCriterion("LSSUEUNIT not between", value1, value2, "LSSUEUNIT");
            return (Criteria) this;
        }

        public Criteria andDRUGSTORENAMEIsNull() {
            addCriterion("DRUGSTORENAME is null");
            return (Criteria) this;
        }

        public Criteria andDRUGSTORENAMEIsNotNull() {
            addCriterion("DRUGSTORENAME is not null");
            return (Criteria) this;
        }

        public Criteria andDRUGSTORENAMEEqualTo(String value) {
            addCriterion("DRUGSTORENAME =", value, "DRUGSTORENAME");
            return (Criteria) this;
        }

        public Criteria andDRUGSTORENAMENotEqualTo(String value) {
            addCriterion("DRUGSTORENAME <>", value, "DRUGSTORENAME");
            return (Criteria) this;
        }

        public Criteria andDRUGSTORENAMEGreaterThan(String value) {
            addCriterion("DRUGSTORENAME >", value, "DRUGSTORENAME");
            return (Criteria) this;
        }

        public Criteria andDRUGSTORENAMEGreaterThanOrEqualTo(String value) {
            addCriterion("DRUGSTORENAME >=", value, "DRUGSTORENAME");
            return (Criteria) this;
        }

        public Criteria andDRUGSTORENAMELessThan(String value) {
            addCriterion("DRUGSTORENAME <", value, "DRUGSTORENAME");
            return (Criteria) this;
        }

        public Criteria andDRUGSTORENAMELessThanOrEqualTo(String value) {
            addCriterion("DRUGSTORENAME <=", value, "DRUGSTORENAME");
            return (Criteria) this;
        }

        public Criteria andDRUGSTORENAMELike(String value) {
            addCriterion("DRUGSTORENAME like", value, "DRUGSTORENAME");
            return (Criteria) this;
        }

        public Criteria andDRUGSTORENAMENotLike(String value) {
            addCriterion("DRUGSTORENAME not like", value, "DRUGSTORENAME");
            return (Criteria) this;
        }

        public Criteria andDRUGSTORENAMEIn(List values) {
            addCriterion("DRUGSTORENAME in", values, "DRUGSTORENAME");
            return (Criteria) this;
        }

        public Criteria andDRUGSTORENAMENotIn(List values) {
            addCriterion("DRUGSTORENAME not in", values, "DRUGSTORENAME");
            return (Criteria) this;
        }

        public Criteria andDRUGSTORENAMEBetween(String value1, String value2) {
            addCriterion("DRUGSTORENAME between", value1, value2, "DRUGSTORENAME");
            return (Criteria) this;
        }

        public Criteria andDRUGSTORENAMENotBetween(String value1, String value2) {
            addCriterion("DRUGSTORENAME not between", value1, value2, "DRUGSTORENAME");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PHARMACIST
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 09 13:50:58 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}