package com.wildwolf.model;

import java.math.BigDecimal;
import java.util.Date;

import com.wildwolf.helper.page.Page;

public class Pharmacist extends Page{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.USERID
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private String USERID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.DRUGSTOREID
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private String DRUGSTOREID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.PHNAME
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private String PHNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.TEL
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private String TEL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.ADDRESS
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private String ADDRESS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.AGE
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private BigDecimal AGE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.CREATEDATE
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private Date CREATEDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.UPDATEDATE
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private Date UPDATEDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.FINGERPRINT
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private String FINGERPRINT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.SEX
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private BigDecimal SEX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.CERTIFICATEID
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private String CERTIFICATEID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.NATIVEPLACE
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private String NATIVEPLACE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.POSITION
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private String POSITION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.EDUCATION
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private String EDUCATION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.GRADUATE
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private String GRADUATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.IDCARDNO
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private String IDCARDNO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.BIRTHDAY
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private Date BIRTHDAY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.QUALIFICATION
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private String QUALIFICATION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.LSSUEUNIT
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private String LSSUEUNIT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHARMACIST.DRUGSTORENAME
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    private String DRUGSTORENAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.USERID
     *
     * @return the value of PHARMACIST.USERID
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public String getUSERID() {
        return USERID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.USERID
     *
     * @param USERID the value for PHARMACIST.USERID
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setUSERID(String USERID) {
        this.USERID = USERID == null ? null : USERID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.DRUGSTOREID
     *
     * @return the value of PHARMACIST.DRUGSTOREID
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public String getDRUGSTOREID() {
        return DRUGSTOREID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.DRUGSTOREID
     *
     * @param DRUGSTOREID the value for PHARMACIST.DRUGSTOREID
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setDRUGSTOREID(String DRUGSTOREID) {
        this.DRUGSTOREID = DRUGSTOREID == null ? null : DRUGSTOREID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.PHNAME
     *
     * @return the value of PHARMACIST.PHNAME
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public String getPHNAME() {
        return PHNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.PHNAME
     *
     * @param PHNAME the value for PHARMACIST.PHNAME
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setPHNAME(String PHNAME) {
        this.PHNAME = PHNAME == null ? null : PHNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.TEL
     *
     * @return the value of PHARMACIST.TEL
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public String getTEL() {
        return TEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.TEL
     *
     * @param TEL the value for PHARMACIST.TEL
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setTEL(String TEL) {
        this.TEL = TEL == null ? null : TEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.ADDRESS
     *
     * @return the value of PHARMACIST.ADDRESS
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public String getADDRESS() {
        return ADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.ADDRESS
     *
     * @param ADDRESS the value for PHARMACIST.ADDRESS
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setADDRESS(String ADDRESS) {
        this.ADDRESS = ADDRESS == null ? null : ADDRESS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.AGE
     *
     * @return the value of PHARMACIST.AGE
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public BigDecimal getAGE() {
        return AGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.AGE
     *
     * @param AGE the value for PHARMACIST.AGE
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setAGE(BigDecimal AGE) {
        this.AGE = AGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.CREATEDATE
     *
     * @return the value of PHARMACIST.CREATEDATE
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public Date getCREATEDATE() {
        return CREATEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.CREATEDATE
     *
     * @param CREATEDATE the value for PHARMACIST.CREATEDATE
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setCREATEDATE(Date CREATEDATE) {
        this.CREATEDATE = CREATEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.UPDATEDATE
     *
     * @return the value of PHARMACIST.UPDATEDATE
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public Date getUPDATEDATE() {
        return UPDATEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.UPDATEDATE
     *
     * @param UPDATEDATE the value for PHARMACIST.UPDATEDATE
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setUPDATEDATE(Date UPDATEDATE) {
        this.UPDATEDATE = UPDATEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.FINGERPRINT
     *
     * @return the value of PHARMACIST.FINGERPRINT
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public String getFINGERPRINT() {
        return FINGERPRINT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.FINGERPRINT
     *
     * @param FINGERPRINT the value for PHARMACIST.FINGERPRINT
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setFINGERPRINT(String FINGERPRINT) {
        this.FINGERPRINT = FINGERPRINT == null ? null : FINGERPRINT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.SEX
     *
     * @return the value of PHARMACIST.SEX
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public BigDecimal getSEX() {
        return SEX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.SEX
     *
     * @param SEX the value for PHARMACIST.SEX
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setSEX(BigDecimal SEX) {
        this.SEX = SEX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.CERTIFICATEID
     *
     * @return the value of PHARMACIST.CERTIFICATEID
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public String getCERTIFICATEID() {
        return CERTIFICATEID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.CERTIFICATEID
     *
     * @param CERTIFICATEID the value for PHARMACIST.CERTIFICATEID
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setCERTIFICATEID(String CERTIFICATEID) {
        this.CERTIFICATEID = CERTIFICATEID == null ? null : CERTIFICATEID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.NATIVEPLACE
     *
     * @return the value of PHARMACIST.NATIVEPLACE
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public String getNATIVEPLACE() {
        return NATIVEPLACE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.NATIVEPLACE
     *
     * @param NATIVEPLACE the value for PHARMACIST.NATIVEPLACE
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setNATIVEPLACE(String NATIVEPLACE) {
        this.NATIVEPLACE = NATIVEPLACE == null ? null : NATIVEPLACE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.POSITION
     *
     * @return the value of PHARMACIST.POSITION
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public String getPOSITION() {
        return POSITION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.POSITION
     *
     * @param POSITION the value for PHARMACIST.POSITION
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setPOSITION(String POSITION) {
        this.POSITION = POSITION == null ? null : POSITION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.EDUCATION
     *
     * @return the value of PHARMACIST.EDUCATION
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public String getEDUCATION() {
        return EDUCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.EDUCATION
     *
     * @param EDUCATION the value for PHARMACIST.EDUCATION
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setEDUCATION(String EDUCATION) {
        this.EDUCATION = EDUCATION == null ? null : EDUCATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.GRADUATE
     *
     * @return the value of PHARMACIST.GRADUATE
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public String getGRADUATE() {
        return GRADUATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.GRADUATE
     *
     * @param GRADUATE the value for PHARMACIST.GRADUATE
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setGRADUATE(String GRADUATE) {
        this.GRADUATE = GRADUATE == null ? null : GRADUATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.IDCARDNO
     *
     * @return the value of PHARMACIST.IDCARDNO
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public String getIDCARDNO() {
        return IDCARDNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.IDCARDNO
     *
     * @param IDCARDNO the value for PHARMACIST.IDCARDNO
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setIDCARDNO(String IDCARDNO) {
        this.IDCARDNO = IDCARDNO == null ? null : IDCARDNO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.BIRTHDAY
     *
     * @return the value of PHARMACIST.BIRTHDAY
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public Date getBIRTHDAY() {
        return BIRTHDAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.BIRTHDAY
     *
     * @param BIRTHDAY the value for PHARMACIST.BIRTHDAY
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setBIRTHDAY(Date BIRTHDAY) {
        this.BIRTHDAY = BIRTHDAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.QUALIFICATION
     *
     * @return the value of PHARMACIST.QUALIFICATION
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public String getQUALIFICATION() {
        return QUALIFICATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.QUALIFICATION
     *
     * @param QUALIFICATION the value for PHARMACIST.QUALIFICATION
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setQUALIFICATION(String QUALIFICATION) {
        this.QUALIFICATION = QUALIFICATION == null ? null : QUALIFICATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.LSSUEUNIT
     *
     * @return the value of PHARMACIST.LSSUEUNIT
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public String getLSSUEUNIT() {
        return LSSUEUNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.LSSUEUNIT
     *
     * @param LSSUEUNIT the value for PHARMACIST.LSSUEUNIT
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setLSSUEUNIT(String LSSUEUNIT) {
        this.LSSUEUNIT = LSSUEUNIT == null ? null : LSSUEUNIT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHARMACIST.DRUGSTORENAME
     *
     * @return the value of PHARMACIST.DRUGSTORENAME
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public String getDRUGSTORENAME() {
        return DRUGSTORENAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHARMACIST.DRUGSTORENAME
     *
     * @param DRUGSTORENAME the value for PHARMACIST.DRUGSTORENAME
     *
     * @mbggenerated Wed Jan 09 13:50:58 CST 2013
     */
    public void setDRUGSTORENAME(String DRUGSTORENAME) {
        this.DRUGSTORENAME = DRUGSTORENAME == null ? null : DRUGSTORENAME.trim();
    }
}