package com.wildwolf.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ROLE
     *
     * @mbggenerated Wed Jan 16 15:56:39 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ROLE
     *
     * @mbggenerated Wed Jan 16 15:56:39 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ROLE
     *
     * @mbggenerated Wed Jan 16 15:56:39 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Wed Jan 16 15:56:39 CST 2013
     */
    public RoleExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Wed Jan 16 15:56:39 CST 2013
     */
    protected RoleExample(RoleExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.distinct = example.distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Wed Jan 16 15:56:39 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Wed Jan 16 15:56:39 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Wed Jan 16 15:56:39 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Wed Jan 16 15:56:39 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Wed Jan 16 15:56:39 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Wed Jan 16 15:56:39 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Wed Jan 16 15:56:39 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Wed Jan 16 15:56:39 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Wed Jan 16 15:56:39 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Wed Jan 16 15:56:39 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ROLE
     *
     * @mbggenerated Wed Jan 16 15:56:39 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected GeneratedCriteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(String value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(String value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(String value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(String value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLike(String value) {
            addCriterion("ID like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotLike(String value) {
            addCriterion("ID not like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andROLENAMEIsNull() {
            addCriterion("ROLENAME is null");
            return (Criteria) this;
        }

        public Criteria andROLENAMEIsNotNull() {
            addCriterion("ROLENAME is not null");
            return (Criteria) this;
        }

        public Criteria andROLENAMEEqualTo(String value) {
            addCriterion("ROLENAME =", value, "ROLENAME");
            return (Criteria) this;
        }

        public Criteria andROLENAMENotEqualTo(String value) {
            addCriterion("ROLENAME <>", value, "ROLENAME");
            return (Criteria) this;
        }

        public Criteria andROLENAMEGreaterThan(String value) {
            addCriterion("ROLENAME >", value, "ROLENAME");
            return (Criteria) this;
        }

        public Criteria andROLENAMEGreaterThanOrEqualTo(String value) {
            addCriterion("ROLENAME >=", value, "ROLENAME");
            return (Criteria) this;
        }

        public Criteria andROLENAMELessThan(String value) {
            addCriterion("ROLENAME <", value, "ROLENAME");
            return (Criteria) this;
        }

        public Criteria andROLENAMELessThanOrEqualTo(String value) {
            addCriterion("ROLENAME <=", value, "ROLENAME");
            return (Criteria) this;
        }

        public Criteria andROLENAMELike(String value) {
            addCriterion("ROLENAME like", value, "ROLENAME");
            return (Criteria) this;
        }

        public Criteria andROLENAMENotLike(String value) {
            addCriterion("ROLENAME not like", value, "ROLENAME");
            return (Criteria) this;
        }

        public Criteria andROLENAMEIn(List values) {
            addCriterion("ROLENAME in", values, "ROLENAME");
            return (Criteria) this;
        }

        public Criteria andROLENAMENotIn(List values) {
            addCriterion("ROLENAME not in", values, "ROLENAME");
            return (Criteria) this;
        }

        public Criteria andROLENAMEBetween(String value1, String value2) {
            addCriterion("ROLENAME between", value1, value2, "ROLENAME");
            return (Criteria) this;
        }

        public Criteria andROLENAMENotBetween(String value1, String value2) {
            addCriterion("ROLENAME not between", value1, value2, "ROLENAME");
            return (Criteria) this;
        }

        public Criteria andRIGHTSIsNull() {
            addCriterion("RIGHTS is null");
            return (Criteria) this;
        }

        public Criteria andRIGHTSIsNotNull() {
            addCriterion("RIGHTS is not null");
            return (Criteria) this;
        }

        public Criteria andRIGHTSEqualTo(String value) {
            addCriterion("RIGHTS =", value, "RIGHTS");
            return (Criteria) this;
        }

        public Criteria andRIGHTSNotEqualTo(String value) {
            addCriterion("RIGHTS <>", value, "RIGHTS");
            return (Criteria) this;
        }

        public Criteria andRIGHTSGreaterThan(String value) {
            addCriterion("RIGHTS >", value, "RIGHTS");
            return (Criteria) this;
        }

        public Criteria andRIGHTSGreaterThanOrEqualTo(String value) {
            addCriterion("RIGHTS >=", value, "RIGHTS");
            return (Criteria) this;
        }

        public Criteria andRIGHTSLessThan(String value) {
            addCriterion("RIGHTS <", value, "RIGHTS");
            return (Criteria) this;
        }

        public Criteria andRIGHTSLessThanOrEqualTo(String value) {
            addCriterion("RIGHTS <=", value, "RIGHTS");
            return (Criteria) this;
        }

        public Criteria andRIGHTSLike(String value) {
            addCriterion("RIGHTS like", value, "RIGHTS");
            return (Criteria) this;
        }

        public Criteria andRIGHTSNotLike(String value) {
            addCriterion("RIGHTS not like", value, "RIGHTS");
            return (Criteria) this;
        }

        public Criteria andRIGHTSIn(List values) {
            addCriterion("RIGHTS in", values, "RIGHTS");
            return (Criteria) this;
        }

        public Criteria andRIGHTSNotIn(List values) {
            addCriterion("RIGHTS not in", values, "RIGHTS");
            return (Criteria) this;
        }

        public Criteria andRIGHTSBetween(String value1, String value2) {
            addCriterion("RIGHTS between", value1, value2, "RIGHTS");
            return (Criteria) this;
        }

        public Criteria andRIGHTSNotBetween(String value1, String value2) {
            addCriterion("RIGHTS not between", value1, value2, "RIGHTS");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEIsNull() {
            addCriterion("CREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEIsNotNull() {
            addCriterion("CREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEEqualTo(Date value) {
            addCriterion("CREATETIME =", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMENotEqualTo(Date value) {
            addCriterion("CREATETIME <>", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEGreaterThan(Date value) {
            addCriterion("CREATETIME >", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATETIME >=", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMELessThan(Date value) {
            addCriterion("CREATETIME <", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMELessThanOrEqualTo(Date value) {
            addCriterion("CREATETIME <=", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEIn(List values) {
            addCriterion("CREATETIME in", values, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMENotIn(List values) {
            addCriterion("CREATETIME not in", values, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEBetween(Date value1, Date value2) {
            addCriterion("CREATETIME between", value1, value2, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMENotBetween(Date value1, Date value2) {
            addCriterion("CREATETIME not between", value1, value2, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMEIsNull() {
            addCriterion("UPDATETIME is null");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMEIsNotNull() {
            addCriterion("UPDATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMEEqualTo(Date value) {
            addCriterion("UPDATETIME =", value, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMENotEqualTo(Date value) {
            addCriterion("UPDATETIME <>", value, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMEGreaterThan(Date value) {
            addCriterion("UPDATETIME >", value, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATETIME >=", value, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMELessThan(Date value) {
            addCriterion("UPDATETIME <", value, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMELessThanOrEqualTo(Date value) {
            addCriterion("UPDATETIME <=", value, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMEIn(List values) {
            addCriterion("UPDATETIME in", values, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMENotIn(List values) {
            addCriterion("UPDATETIME not in", values, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMEBetween(Date value1, Date value2) {
            addCriterion("UPDATETIME between", value1, value2, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMENotBetween(Date value1, Date value2) {
            addCriterion("UPDATETIME not between", value1, value2, "UPDATETIME");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ROLE
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 16 15:56:39 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}