package com.wildwolf.model;

import java.util.Date;

import com.wildwolf.helper.page.Page;

public class Teamrecords extends Page{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamrecords.ID
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    private String ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamrecords.TeamID
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    private String teamID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamrecords.OpponentID
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    private String opponentID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamrecords.Wins
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    private Integer wins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamrecords.Draw
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    private Integer draw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamrecords.Losing
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    private Integer losing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamrecords.Goals
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    private Integer goals;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamrecords.Lost
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    private Integer lost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamrecords.CreateTime
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamrecords.UpdateTime
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamrecords.ID
     *
     * @return the value of teamrecords.ID
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public String getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamrecords.ID
     *
     * @param ID the value for teamrecords.ID
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public void setID(String ID) {
        this.ID = ID == null ? null : ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamrecords.TeamID
     *
     * @return the value of teamrecords.TeamID
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public String getTeamID() {
        return teamID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamrecords.TeamID
     *
     * @param teamID the value for teamrecords.TeamID
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public void setTeamID(String teamID) {
        this.teamID = teamID == null ? null : teamID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamrecords.OpponentID
     *
     * @return the value of teamrecords.OpponentID
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public String getOpponentID() {
        return opponentID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamrecords.OpponentID
     *
     * @param opponentID the value for teamrecords.OpponentID
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public void setOpponentID(String opponentID) {
        this.opponentID = opponentID == null ? null : opponentID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamrecords.Wins
     *
     * @return the value of teamrecords.Wins
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public Integer getWins() {
        return wins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamrecords.Wins
     *
     * @param wins the value for teamrecords.Wins
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public void setWins(Integer wins) {
        this.wins = wins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamrecords.Draw
     *
     * @return the value of teamrecords.Draw
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public Integer getDraw() {
        return draw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamrecords.Draw
     *
     * @param draw the value for teamrecords.Draw
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public void setDraw(Integer draw) {
        this.draw = draw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamrecords.Losing
     *
     * @return the value of teamrecords.Losing
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public Integer getLosing() {
        return losing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamrecords.Losing
     *
     * @param losing the value for teamrecords.Losing
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public void setLosing(Integer losing) {
        this.losing = losing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamrecords.Goals
     *
     * @return the value of teamrecords.Goals
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public Integer getGoals() {
        return goals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamrecords.Goals
     *
     * @param goals the value for teamrecords.Goals
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public void setGoals(Integer goals) {
        this.goals = goals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamrecords.Lost
     *
     * @return the value of teamrecords.Lost
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public Integer getLost() {
        return lost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamrecords.Lost
     *
     * @param lost the value for teamrecords.Lost
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public void setLost(Integer lost) {
        this.lost = lost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamrecords.CreateTime
     *
     * @return the value of teamrecords.CreateTime
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamrecords.CreateTime
     *
     * @param createTime the value for teamrecords.CreateTime
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamrecords.UpdateTime
     *
     * @return the value of teamrecords.UpdateTime
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamrecords.UpdateTime
     *
     * @param updateTime the value for teamrecords.UpdateTime
     *
     * @mbggenerated Tue May 28 15:16:33 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}