package com.wildwolf.model;

import java.math.BigDecimal;
import java.util.Date;

import com.wildwolf.helper.page.Page;

public class Team extends Page{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.ID
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    private String ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.TeamName
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    private String teamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.CaptainID
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    private String captainID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.CaptainName
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    private String captainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.Wins
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    private Integer wins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.Draw
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    private Integer draw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.Losing
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    private Integer losing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.Goals
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    private Integer goals;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.Lost
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    private Integer lost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.Balance
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.CreateTime
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.UpdateTime
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.ID
     *
     * @return the value of team.ID
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public String getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.ID
     *
     * @param ID the value for team.ID
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public void setID(String ID) {
        this.ID = ID == null ? null : ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.TeamName
     *
     * @return the value of team.TeamName
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.TeamName
     *
     * @param teamName the value for team.TeamName
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.CaptainID
     *
     * @return the value of team.CaptainID
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public String getCaptainID() {
        return captainID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.CaptainID
     *
     * @param captainID the value for team.CaptainID
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public void setCaptainID(String captainID) {
        this.captainID = captainID == null ? null : captainID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.CaptainName
     *
     * @return the value of team.CaptainName
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public String getCaptainName() {
        return captainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.CaptainName
     *
     * @param captainName the value for team.CaptainName
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public void setCaptainName(String captainName) {
        this.captainName = captainName == null ? null : captainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.Wins
     *
     * @return the value of team.Wins
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public Integer getWins() {
        return wins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.Wins
     *
     * @param wins the value for team.Wins
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public void setWins(Integer wins) {
        this.wins = wins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.Draw
     *
     * @return the value of team.Draw
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public Integer getDraw() {
        return draw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.Draw
     *
     * @param draw the value for team.Draw
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public void setDraw(Integer draw) {
        this.draw = draw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.Losing
     *
     * @return the value of team.Losing
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public Integer getLosing() {
        return losing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.Losing
     *
     * @param losing the value for team.Losing
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public void setLosing(Integer losing) {
        this.losing = losing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.Goals
     *
     * @return the value of team.Goals
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public Integer getGoals() {
        return goals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.Goals
     *
     * @param goals the value for team.Goals
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public void setGoals(Integer goals) {
        this.goals = goals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.Lost
     *
     * @return the value of team.Lost
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public Integer getLost() {
        return lost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.Lost
     *
     * @param lost the value for team.Lost
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public void setLost(Integer lost) {
        this.lost = lost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.Balance
     *
     * @return the value of team.Balance
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.Balance
     *
     * @param balance the value for team.Balance
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.CreateTime
     *
     * @return the value of team.CreateTime
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.CreateTime
     *
     * @param createTime the value for team.CreateTime
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.UpdateTime
     *
     * @return the value of team.UpdateTime
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.UpdateTime
     *
     * @param updateTime the value for team.UpdateTime
     *
     * @mbggenerated Thu Jun 06 14:45:21 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}