package com.wildwolf.model;

import java.math.BigDecimal;
import java.util.Date;

import com.wildwolf.helper.page.Page;

public class Tuser extends Page{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.ID
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private String ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.USERNAME
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private String USERNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.REALNAME
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private String REALNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.PASSWORD
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private String PASSWORD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.ROLEID
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private String ROLEID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.ADDRESS
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private String ADDRESS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.TEL
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private String TEL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.BIRTHDAY
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private String BIRTHDAY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.SEX
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private Integer SEX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.PICURL
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private String PICURL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.TEAMID
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private String TEAMID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.TEAMNAME
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private String TEAMNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.GOALS
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private Integer GOALS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.ASSIST
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private Integer ASSIST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.BALANCE
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private BigDecimal BALANCE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.PLAYTIMES
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private Integer PLAYTIMES;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.CREATETIME
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private Date CREATETIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.UPDATETIME
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    private Date UPDATETIME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.ID
     *
     * @return the value of tuser.ID
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public String getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.ID
     *
     * @param ID the value for tuser.ID
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setID(String ID) {
        this.ID = ID == null ? null : ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.USERNAME
     *
     * @return the value of tuser.USERNAME
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public String getUSERNAME() {
        return USERNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.USERNAME
     *
     * @param USERNAME the value for tuser.USERNAME
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setUSERNAME(String USERNAME) {
        this.USERNAME = USERNAME == null ? null : USERNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.REALNAME
     *
     * @return the value of tuser.REALNAME
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public String getREALNAME() {
        return REALNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.REALNAME
     *
     * @param REALNAME the value for tuser.REALNAME
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setREALNAME(String REALNAME) {
        this.REALNAME = REALNAME == null ? null : REALNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.PASSWORD
     *
     * @return the value of tuser.PASSWORD
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public String getPASSWORD() {
        return PASSWORD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.PASSWORD
     *
     * @param PASSWORD the value for tuser.PASSWORD
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setPASSWORD(String PASSWORD) {
        this.PASSWORD = PASSWORD == null ? null : PASSWORD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.ROLEID
     *
     * @return the value of tuser.ROLEID
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public String getROLEID() {
        return ROLEID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.ROLEID
     *
     * @param ROLEID the value for tuser.ROLEID
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setROLEID(String ROLEID) {
        this.ROLEID = ROLEID == null ? null : ROLEID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.ADDRESS
     *
     * @return the value of tuser.ADDRESS
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public String getADDRESS() {
        return ADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.ADDRESS
     *
     * @param ADDRESS the value for tuser.ADDRESS
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setADDRESS(String ADDRESS) {
        this.ADDRESS = ADDRESS == null ? null : ADDRESS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.TEL
     *
     * @return the value of tuser.TEL
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public String getTEL() {
        return TEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.TEL
     *
     * @param TEL the value for tuser.TEL
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setTEL(String TEL) {
        this.TEL = TEL == null ? null : TEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.BIRTHDAY
     *
     * @return the value of tuser.BIRTHDAY
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public String getBIRTHDAY() {
        return BIRTHDAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.BIRTHDAY
     *
     * @param BIRTHDAY the value for tuser.BIRTHDAY
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setBIRTHDAY(String BIRTHDAY) {
        this.BIRTHDAY = BIRTHDAY == null ? null : BIRTHDAY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.SEX
     *
     * @return the value of tuser.SEX
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public Integer getSEX() {
        return SEX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.SEX
     *
     * @param SEX the value for tuser.SEX
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setSEX(Integer SEX) {
        this.SEX = SEX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.PICURL
     *
     * @return the value of tuser.PICURL
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public String getPICURL() {
        return PICURL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.PICURL
     *
     * @param PICURL the value for tuser.PICURL
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setPICURL(String PICURL) {
        this.PICURL = PICURL == null ? null : PICURL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.TEAMID
     *
     * @return the value of tuser.TEAMID
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public String getTEAMID() {
        return TEAMID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.TEAMID
     *
     * @param TEAMID the value for tuser.TEAMID
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setTEAMID(String TEAMID) {
        this.TEAMID = TEAMID == null ? null : TEAMID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.TEAMNAME
     *
     * @return the value of tuser.TEAMNAME
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public String getTEAMNAME() {
        return TEAMNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.TEAMNAME
     *
     * @param TEAMNAME the value for tuser.TEAMNAME
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setTEAMNAME(String TEAMNAME) {
        this.TEAMNAME = TEAMNAME == null ? null : TEAMNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.GOALS
     *
     * @return the value of tuser.GOALS
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public Integer getGOALS() {
        return GOALS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.GOALS
     *
     * @param GOALS the value for tuser.GOALS
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setGOALS(Integer GOALS) {
        this.GOALS = GOALS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.ASSIST
     *
     * @return the value of tuser.ASSIST
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public Integer getASSIST() {
        return ASSIST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.ASSIST
     *
     * @param ASSIST the value for tuser.ASSIST
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setASSIST(Integer ASSIST) {
        this.ASSIST = ASSIST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.BALANCE
     *
     * @return the value of tuser.BALANCE
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public BigDecimal getBALANCE() {
        return BALANCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.BALANCE
     *
     * @param BALANCE the value for tuser.BALANCE
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setBALANCE(BigDecimal BALANCE) {
        this.BALANCE = BALANCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.PLAYTIMES
     *
     * @return the value of tuser.PLAYTIMES
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public Integer getPLAYTIMES() {
        return PLAYTIMES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.PLAYTIMES
     *
     * @param PLAYTIMES the value for tuser.PLAYTIMES
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setPLAYTIMES(Integer PLAYTIMES) {
        this.PLAYTIMES = PLAYTIMES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.CREATETIME
     *
     * @return the value of tuser.CREATETIME
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public Date getCREATETIME() {
        return CREATETIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.CREATETIME
     *
     * @param CREATETIME the value for tuser.CREATETIME
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setCREATETIME(Date CREATETIME) {
        this.CREATETIME = CREATETIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.UPDATETIME
     *
     * @return the value of tuser.UPDATETIME
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public Date getUPDATETIME() {
        return UPDATETIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.UPDATETIME
     *
     * @param UPDATETIME the value for tuser.UPDATETIME
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setUPDATETIME(Date UPDATETIME) {
        this.UPDATETIME = UPDATETIME;
    }
}