package com.wildwolf.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TuserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tuser
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tuser
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tuser
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public TuserExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    protected TuserExample(TuserExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.distinct = example.distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tuser
     *
     * @mbggenerated Tue May 14 16:04:15 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected GeneratedCriteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(String value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(String value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(String value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(String value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLike(String value) {
            addCriterion("ID like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotLike(String value) {
            addCriterion("ID not like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andUSERNAMEIsNull() {
            addCriterion("USERNAME is null");
            return (Criteria) this;
        }

        public Criteria andUSERNAMEIsNotNull() {
            addCriterion("USERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUSERNAMEEqualTo(String value) {
            addCriterion("USERNAME =", value, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMENotEqualTo(String value) {
            addCriterion("USERNAME <>", value, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMEGreaterThan(String value) {
            addCriterion("USERNAME >", value, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMEGreaterThanOrEqualTo(String value) {
            addCriterion("USERNAME >=", value, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMELessThan(String value) {
            addCriterion("USERNAME <", value, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMELessThanOrEqualTo(String value) {
            addCriterion("USERNAME <=", value, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMELike(String value) {
            addCriterion("USERNAME like", value, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMENotLike(String value) {
            addCriterion("USERNAME not like", value, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMEIn(List values) {
            addCriterion("USERNAME in", values, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMENotIn(List values) {
            addCriterion("USERNAME not in", values, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMEBetween(String value1, String value2) {
            addCriterion("USERNAME between", value1, value2, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMENotBetween(String value1, String value2) {
            addCriterion("USERNAME not between", value1, value2, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andREALNAMEIsNull() {
            addCriterion("REALNAME is null");
            return (Criteria) this;
        }

        public Criteria andREALNAMEIsNotNull() {
            addCriterion("REALNAME is not null");
            return (Criteria) this;
        }

        public Criteria andREALNAMEEqualTo(String value) {
            addCriterion("REALNAME =", value, "REALNAME");
            return (Criteria) this;
        }

        public Criteria andREALNAMENotEqualTo(String value) {
            addCriterion("REALNAME <>", value, "REALNAME");
            return (Criteria) this;
        }

        public Criteria andREALNAMEGreaterThan(String value) {
            addCriterion("REALNAME >", value, "REALNAME");
            return (Criteria) this;
        }

        public Criteria andREALNAMEGreaterThanOrEqualTo(String value) {
            addCriterion("REALNAME >=", value, "REALNAME");
            return (Criteria) this;
        }

        public Criteria andREALNAMELessThan(String value) {
            addCriterion("REALNAME <", value, "REALNAME");
            return (Criteria) this;
        }

        public Criteria andREALNAMELessThanOrEqualTo(String value) {
            addCriterion("REALNAME <=", value, "REALNAME");
            return (Criteria) this;
        }

        public Criteria andREALNAMELike(String value) {
            addCriterion("REALNAME like", value, "REALNAME");
            return (Criteria) this;
        }

        public Criteria andREALNAMENotLike(String value) {
            addCriterion("REALNAME not like", value, "REALNAME");
            return (Criteria) this;
        }

        public Criteria andREALNAMEIn(List values) {
            addCriterion("REALNAME in", values, "REALNAME");
            return (Criteria) this;
        }

        public Criteria andREALNAMENotIn(List values) {
            addCriterion("REALNAME not in", values, "REALNAME");
            return (Criteria) this;
        }

        public Criteria andREALNAMEBetween(String value1, String value2) {
            addCriterion("REALNAME between", value1, value2, "REALNAME");
            return (Criteria) this;
        }

        public Criteria andREALNAMENotBetween(String value1, String value2) {
            addCriterion("REALNAME not between", value1, value2, "REALNAME");
            return (Criteria) this;
        }

        public Criteria andPASSWORDIsNull() {
            addCriterion("PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andPASSWORDIsNotNull() {
            addCriterion("PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andPASSWORDEqualTo(String value) {
            addCriterion("PASSWORD =", value, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDNotEqualTo(String value) {
            addCriterion("PASSWORD <>", value, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDGreaterThan(String value) {
            addCriterion("PASSWORD >", value, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWORD >=", value, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDLessThan(String value) {
            addCriterion("PASSWORD <", value, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDLessThanOrEqualTo(String value) {
            addCriterion("PASSWORD <=", value, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDLike(String value) {
            addCriterion("PASSWORD like", value, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDNotLike(String value) {
            addCriterion("PASSWORD not like", value, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDIn(List values) {
            addCriterion("PASSWORD in", values, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDNotIn(List values) {
            addCriterion("PASSWORD not in", values, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDBetween(String value1, String value2) {
            addCriterion("PASSWORD between", value1, value2, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDNotBetween(String value1, String value2) {
            addCriterion("PASSWORD not between", value1, value2, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andROLEIDIsNull() {
            addCriterion("ROLEID is null");
            return (Criteria) this;
        }

        public Criteria andROLEIDIsNotNull() {
            addCriterion("ROLEID is not null");
            return (Criteria) this;
        }

        public Criteria andROLEIDEqualTo(String value) {
            addCriterion("ROLEID =", value, "ROLEID");
            return (Criteria) this;
        }

        public Criteria andROLEIDNotEqualTo(String value) {
            addCriterion("ROLEID <>", value, "ROLEID");
            return (Criteria) this;
        }

        public Criteria andROLEIDGreaterThan(String value) {
            addCriterion("ROLEID >", value, "ROLEID");
            return (Criteria) this;
        }

        public Criteria andROLEIDGreaterThanOrEqualTo(String value) {
            addCriterion("ROLEID >=", value, "ROLEID");
            return (Criteria) this;
        }

        public Criteria andROLEIDLessThan(String value) {
            addCriterion("ROLEID <", value, "ROLEID");
            return (Criteria) this;
        }

        public Criteria andROLEIDLessThanOrEqualTo(String value) {
            addCriterion("ROLEID <=", value, "ROLEID");
            return (Criteria) this;
        }

        public Criteria andROLEIDLike(String value) {
            addCriterion("ROLEID like", value, "ROLEID");
            return (Criteria) this;
        }

        public Criteria andROLEIDNotLike(String value) {
            addCriterion("ROLEID not like", value, "ROLEID");
            return (Criteria) this;
        }

        public Criteria andROLEIDIn(List values) {
            addCriterion("ROLEID in", values, "ROLEID");
            return (Criteria) this;
        }

        public Criteria andROLEIDNotIn(List values) {
            addCriterion("ROLEID not in", values, "ROLEID");
            return (Criteria) this;
        }

        public Criteria andROLEIDBetween(String value1, String value2) {
            addCriterion("ROLEID between", value1, value2, "ROLEID");
            return (Criteria) this;
        }

        public Criteria andROLEIDNotBetween(String value1, String value2) {
            addCriterion("ROLEID not between", value1, value2, "ROLEID");
            return (Criteria) this;
        }

        public Criteria andADDRESSIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andADDRESSIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andADDRESSEqualTo(String value) {
            addCriterion("ADDRESS =", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSLessThan(String value) {
            addCriterion("ADDRESS <", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSLike(String value) {
            addCriterion("ADDRESS like", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSNotLike(String value) {
            addCriterion("ADDRESS not like", value, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSIn(List values) {
            addCriterion("ADDRESS in", values, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSNotIn(List values) {
            addCriterion("ADDRESS not in", values, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andADDRESSNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "ADDRESS");
            return (Criteria) this;
        }

        public Criteria andTELIsNull() {
            addCriterion("TEL is null");
            return (Criteria) this;
        }

        public Criteria andTELIsNotNull() {
            addCriterion("TEL is not null");
            return (Criteria) this;
        }

        public Criteria andTELEqualTo(String value) {
            addCriterion("TEL =", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELNotEqualTo(String value) {
            addCriterion("TEL <>", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELGreaterThan(String value) {
            addCriterion("TEL >", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELGreaterThanOrEqualTo(String value) {
            addCriterion("TEL >=", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELLessThan(String value) {
            addCriterion("TEL <", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELLessThanOrEqualTo(String value) {
            addCriterion("TEL <=", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELLike(String value) {
            addCriterion("TEL like", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELNotLike(String value) {
            addCriterion("TEL not like", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELIn(List values) {
            addCriterion("TEL in", values, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELNotIn(List values) {
            addCriterion("TEL not in", values, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELBetween(String value1, String value2) {
            addCriterion("TEL between", value1, value2, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELNotBetween(String value1, String value2) {
            addCriterion("TEL not between", value1, value2, "TEL");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYIsNull() {
            addCriterion("BIRTHDAY is null");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYIsNotNull() {
            addCriterion("BIRTHDAY is not null");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYEqualTo(String value) {
            addCriterion("BIRTHDAY =", value, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYNotEqualTo(String value) {
            addCriterion("BIRTHDAY <>", value, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYGreaterThan(String value) {
            addCriterion("BIRTHDAY >", value, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYGreaterThanOrEqualTo(String value) {
            addCriterion("BIRTHDAY >=", value, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYLessThan(String value) {
            addCriterion("BIRTHDAY <", value, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYLessThanOrEqualTo(String value) {
            addCriterion("BIRTHDAY <=", value, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYLike(String value) {
            addCriterion("BIRTHDAY like", value, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYNotLike(String value) {
            addCriterion("BIRTHDAY not like", value, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYIn(List values) {
            addCriterion("BIRTHDAY in", values, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYNotIn(List values) {
            addCriterion("BIRTHDAY not in", values, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYBetween(String value1, String value2) {
            addCriterion("BIRTHDAY between", value1, value2, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andBIRTHDAYNotBetween(String value1, String value2) {
            addCriterion("BIRTHDAY not between", value1, value2, "BIRTHDAY");
            return (Criteria) this;
        }

        public Criteria andSEXIsNull() {
            addCriterion("SEX is null");
            return (Criteria) this;
        }

        public Criteria andSEXIsNotNull() {
            addCriterion("SEX is not null");
            return (Criteria) this;
        }

        public Criteria andSEXEqualTo(Integer value) {
            addCriterion("SEX =", value, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXNotEqualTo(Integer value) {
            addCriterion("SEX <>", value, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXGreaterThan(Integer value) {
            addCriterion("SEX >", value, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXGreaterThanOrEqualTo(Integer value) {
            addCriterion("SEX >=", value, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXLessThan(Integer value) {
            addCriterion("SEX <", value, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXLessThanOrEqualTo(Integer value) {
            addCriterion("SEX <=", value, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXIn(List values) {
            addCriterion("SEX in", values, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXNotIn(List values) {
            addCriterion("SEX not in", values, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXBetween(Integer value1, Integer value2) {
            addCriterion("SEX between", value1, value2, "SEX");
            return (Criteria) this;
        }

        public Criteria andSEXNotBetween(Integer value1, Integer value2) {
            addCriterion("SEX not between", value1, value2, "SEX");
            return (Criteria) this;
        }

        public Criteria andPICURLIsNull() {
            addCriterion("PICURL is null");
            return (Criteria) this;
        }

        public Criteria andPICURLIsNotNull() {
            addCriterion("PICURL is not null");
            return (Criteria) this;
        }

        public Criteria andPICURLEqualTo(String value) {
            addCriterion("PICURL =", value, "PICURL");
            return (Criteria) this;
        }

        public Criteria andPICURLNotEqualTo(String value) {
            addCriterion("PICURL <>", value, "PICURL");
            return (Criteria) this;
        }

        public Criteria andPICURLGreaterThan(String value) {
            addCriterion("PICURL >", value, "PICURL");
            return (Criteria) this;
        }

        public Criteria andPICURLGreaterThanOrEqualTo(String value) {
            addCriterion("PICURL >=", value, "PICURL");
            return (Criteria) this;
        }

        public Criteria andPICURLLessThan(String value) {
            addCriterion("PICURL <", value, "PICURL");
            return (Criteria) this;
        }

        public Criteria andPICURLLessThanOrEqualTo(String value) {
            addCriterion("PICURL <=", value, "PICURL");
            return (Criteria) this;
        }

        public Criteria andPICURLLike(String value) {
            addCriterion("PICURL like", value, "PICURL");
            return (Criteria) this;
        }

        public Criteria andPICURLNotLike(String value) {
            addCriterion("PICURL not like", value, "PICURL");
            return (Criteria) this;
        }

        public Criteria andPICURLIn(List values) {
            addCriterion("PICURL in", values, "PICURL");
            return (Criteria) this;
        }

        public Criteria andPICURLNotIn(List values) {
            addCriterion("PICURL not in", values, "PICURL");
            return (Criteria) this;
        }

        public Criteria andPICURLBetween(String value1, String value2) {
            addCriterion("PICURL between", value1, value2, "PICURL");
            return (Criteria) this;
        }

        public Criteria andPICURLNotBetween(String value1, String value2) {
            addCriterion("PICURL not between", value1, value2, "PICURL");
            return (Criteria) this;
        }

        public Criteria andTEAMIDIsNull() {
            addCriterion("TEAMID is null");
            return (Criteria) this;
        }

        public Criteria andTEAMIDIsNotNull() {
            addCriterion("TEAMID is not null");
            return (Criteria) this;
        }

        public Criteria andTEAMIDEqualTo(String value) {
            addCriterion("TEAMID =", value, "TEAMID");
            return (Criteria) this;
        }

        public Criteria andTEAMIDNotEqualTo(String value) {
            addCriterion("TEAMID <>", value, "TEAMID");
            return (Criteria) this;
        }

        public Criteria andTEAMIDGreaterThan(String value) {
            addCriterion("TEAMID >", value, "TEAMID");
            return (Criteria) this;
        }

        public Criteria andTEAMIDGreaterThanOrEqualTo(String value) {
            addCriterion("TEAMID >=", value, "TEAMID");
            return (Criteria) this;
        }

        public Criteria andTEAMIDLessThan(String value) {
            addCriterion("TEAMID <", value, "TEAMID");
            return (Criteria) this;
        }

        public Criteria andTEAMIDLessThanOrEqualTo(String value) {
            addCriterion("TEAMID <=", value, "TEAMID");
            return (Criteria) this;
        }

        public Criteria andTEAMIDLike(String value) {
            addCriterion("TEAMID like", value, "TEAMID");
            return (Criteria) this;
        }

        public Criteria andTEAMIDNotLike(String value) {
            addCriterion("TEAMID not like", value, "TEAMID");
            return (Criteria) this;
        }

        public Criteria andTEAMIDIn(List values) {
            addCriterion("TEAMID in", values, "TEAMID");
            return (Criteria) this;
        }

        public Criteria andTEAMIDNotIn(List values) {
            addCriterion("TEAMID not in", values, "TEAMID");
            return (Criteria) this;
        }

        public Criteria andTEAMIDBetween(String value1, String value2) {
            addCriterion("TEAMID between", value1, value2, "TEAMID");
            return (Criteria) this;
        }

        public Criteria andTEAMIDNotBetween(String value1, String value2) {
            addCriterion("TEAMID not between", value1, value2, "TEAMID");
            return (Criteria) this;
        }

        public Criteria andTEAMNAMEIsNull() {
            addCriterion("TEAMNAME is null");
            return (Criteria) this;
        }

        public Criteria andTEAMNAMEIsNotNull() {
            addCriterion("TEAMNAME is not null");
            return (Criteria) this;
        }

        public Criteria andTEAMNAMEEqualTo(String value) {
            addCriterion("TEAMNAME =", value, "TEAMNAME");
            return (Criteria) this;
        }

        public Criteria andTEAMNAMENotEqualTo(String value) {
            addCriterion("TEAMNAME <>", value, "TEAMNAME");
            return (Criteria) this;
        }

        public Criteria andTEAMNAMEGreaterThan(String value) {
            addCriterion("TEAMNAME >", value, "TEAMNAME");
            return (Criteria) this;
        }

        public Criteria andTEAMNAMEGreaterThanOrEqualTo(String value) {
            addCriterion("TEAMNAME >=", value, "TEAMNAME");
            return (Criteria) this;
        }

        public Criteria andTEAMNAMELessThan(String value) {
            addCriterion("TEAMNAME <", value, "TEAMNAME");
            return (Criteria) this;
        }

        public Criteria andTEAMNAMELessThanOrEqualTo(String value) {
            addCriterion("TEAMNAME <=", value, "TEAMNAME");
            return (Criteria) this;
        }

        public Criteria andTEAMNAMELike(String value) {
            addCriterion("TEAMNAME like", value, "TEAMNAME");
            return (Criteria) this;
        }

        public Criteria andTEAMNAMENotLike(String value) {
            addCriterion("TEAMNAME not like", value, "TEAMNAME");
            return (Criteria) this;
        }

        public Criteria andTEAMNAMEIn(List values) {
            addCriterion("TEAMNAME in", values, "TEAMNAME");
            return (Criteria) this;
        }

        public Criteria andTEAMNAMENotIn(List values) {
            addCriterion("TEAMNAME not in", values, "TEAMNAME");
            return (Criteria) this;
        }

        public Criteria andTEAMNAMEBetween(String value1, String value2) {
            addCriterion("TEAMNAME between", value1, value2, "TEAMNAME");
            return (Criteria) this;
        }

        public Criteria andTEAMNAMENotBetween(String value1, String value2) {
            addCriterion("TEAMNAME not between", value1, value2, "TEAMNAME");
            return (Criteria) this;
        }

        public Criteria andGOALSIsNull() {
            addCriterion("GOALS is null");
            return (Criteria) this;
        }

        public Criteria andGOALSIsNotNull() {
            addCriterion("GOALS is not null");
            return (Criteria) this;
        }

        public Criteria andGOALSEqualTo(Integer value) {
            addCriterion("GOALS =", value, "GOALS");
            return (Criteria) this;
        }

        public Criteria andGOALSNotEqualTo(Integer value) {
            addCriterion("GOALS <>", value, "GOALS");
            return (Criteria) this;
        }

        public Criteria andGOALSGreaterThan(Integer value) {
            addCriterion("GOALS >", value, "GOALS");
            return (Criteria) this;
        }

        public Criteria andGOALSGreaterThanOrEqualTo(Integer value) {
            addCriterion("GOALS >=", value, "GOALS");
            return (Criteria) this;
        }

        public Criteria andGOALSLessThan(Integer value) {
            addCriterion("GOALS <", value, "GOALS");
            return (Criteria) this;
        }

        public Criteria andGOALSLessThanOrEqualTo(Integer value) {
            addCriterion("GOALS <=", value, "GOALS");
            return (Criteria) this;
        }

        public Criteria andGOALSIn(List values) {
            addCriterion("GOALS in", values, "GOALS");
            return (Criteria) this;
        }

        public Criteria andGOALSNotIn(List values) {
            addCriterion("GOALS not in", values, "GOALS");
            return (Criteria) this;
        }

        public Criteria andGOALSBetween(Integer value1, Integer value2) {
            addCriterion("GOALS between", value1, value2, "GOALS");
            return (Criteria) this;
        }

        public Criteria andGOALSNotBetween(Integer value1, Integer value2) {
            addCriterion("GOALS not between", value1, value2, "GOALS");
            return (Criteria) this;
        }

        public Criteria andASSISTIsNull() {
            addCriterion("ASSIST is null");
            return (Criteria) this;
        }

        public Criteria andASSISTIsNotNull() {
            addCriterion("ASSIST is not null");
            return (Criteria) this;
        }

        public Criteria andASSISTEqualTo(Integer value) {
            addCriterion("ASSIST =", value, "ASSIST");
            return (Criteria) this;
        }

        public Criteria andASSISTNotEqualTo(Integer value) {
            addCriterion("ASSIST <>", value, "ASSIST");
            return (Criteria) this;
        }

        public Criteria andASSISTGreaterThan(Integer value) {
            addCriterion("ASSIST >", value, "ASSIST");
            return (Criteria) this;
        }

        public Criteria andASSISTGreaterThanOrEqualTo(Integer value) {
            addCriterion("ASSIST >=", value, "ASSIST");
            return (Criteria) this;
        }

        public Criteria andASSISTLessThan(Integer value) {
            addCriterion("ASSIST <", value, "ASSIST");
            return (Criteria) this;
        }

        public Criteria andASSISTLessThanOrEqualTo(Integer value) {
            addCriterion("ASSIST <=", value, "ASSIST");
            return (Criteria) this;
        }

        public Criteria andASSISTIn(List values) {
            addCriterion("ASSIST in", values, "ASSIST");
            return (Criteria) this;
        }

        public Criteria andASSISTNotIn(List values) {
            addCriterion("ASSIST not in", values, "ASSIST");
            return (Criteria) this;
        }

        public Criteria andASSISTBetween(Integer value1, Integer value2) {
            addCriterion("ASSIST between", value1, value2, "ASSIST");
            return (Criteria) this;
        }

        public Criteria andASSISTNotBetween(Integer value1, Integer value2) {
            addCriterion("ASSIST not between", value1, value2, "ASSIST");
            return (Criteria) this;
        }

        public Criteria andBALANCEIsNull() {
            addCriterion("BALANCE is null");
            return (Criteria) this;
        }

        public Criteria andBALANCEIsNotNull() {
            addCriterion("BALANCE is not null");
            return (Criteria) this;
        }

        public Criteria andBALANCEEqualTo(BigDecimal value) {
            addCriterion("BALANCE =", value, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCENotEqualTo(BigDecimal value) {
            addCriterion("BALANCE <>", value, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCEGreaterThan(BigDecimal value) {
            addCriterion("BALANCE >", value, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCEGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BALANCE >=", value, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCELessThan(BigDecimal value) {
            addCriterion("BALANCE <", value, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCELessThanOrEqualTo(BigDecimal value) {
            addCriterion("BALANCE <=", value, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCEIn(List values) {
            addCriterion("BALANCE in", values, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCENotIn(List values) {
            addCriterion("BALANCE not in", values, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCEBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BALANCE between", value1, value2, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCENotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BALANCE not between", value1, value2, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andPLAYTIMESIsNull() {
            addCriterion("PLAYTIMES is null");
            return (Criteria) this;
        }

        public Criteria andPLAYTIMESIsNotNull() {
            addCriterion("PLAYTIMES is not null");
            return (Criteria) this;
        }

        public Criteria andPLAYTIMESEqualTo(Integer value) {
            addCriterion("PLAYTIMES =", value, "PLAYTIMES");
            return (Criteria) this;
        }

        public Criteria andPLAYTIMESNotEqualTo(Integer value) {
            addCriterion("PLAYTIMES <>", value, "PLAYTIMES");
            return (Criteria) this;
        }

        public Criteria andPLAYTIMESGreaterThan(Integer value) {
            addCriterion("PLAYTIMES >", value, "PLAYTIMES");
            return (Criteria) this;
        }

        public Criteria andPLAYTIMESGreaterThanOrEqualTo(Integer value) {
            addCriterion("PLAYTIMES >=", value, "PLAYTIMES");
            return (Criteria) this;
        }

        public Criteria andPLAYTIMESLessThan(Integer value) {
            addCriterion("PLAYTIMES <", value, "PLAYTIMES");
            return (Criteria) this;
        }

        public Criteria andPLAYTIMESLessThanOrEqualTo(Integer value) {
            addCriterion("PLAYTIMES <=", value, "PLAYTIMES");
            return (Criteria) this;
        }

        public Criteria andPLAYTIMESIn(List values) {
            addCriterion("PLAYTIMES in", values, "PLAYTIMES");
            return (Criteria) this;
        }

        public Criteria andPLAYTIMESNotIn(List values) {
            addCriterion("PLAYTIMES not in", values, "PLAYTIMES");
            return (Criteria) this;
        }

        public Criteria andPLAYTIMESBetween(Integer value1, Integer value2) {
            addCriterion("PLAYTIMES between", value1, value2, "PLAYTIMES");
            return (Criteria) this;
        }

        public Criteria andPLAYTIMESNotBetween(Integer value1, Integer value2) {
            addCriterion("PLAYTIMES not between", value1, value2, "PLAYTIMES");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEIsNull() {
            addCriterion("CREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEIsNotNull() {
            addCriterion("CREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEEqualTo(Date value) {
            addCriterion("CREATETIME =", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMENotEqualTo(Date value) {
            addCriterion("CREATETIME <>", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEGreaterThan(Date value) {
            addCriterion("CREATETIME >", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATETIME >=", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMELessThan(Date value) {
            addCriterion("CREATETIME <", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMELessThanOrEqualTo(Date value) {
            addCriterion("CREATETIME <=", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEIn(List values) {
            addCriterion("CREATETIME in", values, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMENotIn(List values) {
            addCriterion("CREATETIME not in", values, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEBetween(Date value1, Date value2) {
            addCriterion("CREATETIME between", value1, value2, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMENotBetween(Date value1, Date value2) {
            addCriterion("CREATETIME not between", value1, value2, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMEIsNull() {
            addCriterion("UPDATETIME is null");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMEIsNotNull() {
            addCriterion("UPDATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMEEqualTo(Date value) {
            addCriterion("UPDATETIME =", value, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMENotEqualTo(Date value) {
            addCriterion("UPDATETIME <>", value, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMEGreaterThan(Date value) {
            addCriterion("UPDATETIME >", value, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATETIME >=", value, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMELessThan(Date value) {
            addCriterion("UPDATETIME <", value, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMELessThanOrEqualTo(Date value) {
            addCriterion("UPDATETIME <=", value, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMEIn(List values) {
            addCriterion("UPDATETIME in", values, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMENotIn(List values) {
            addCriterion("UPDATETIME not in", values, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMEBetween(Date value1, Date value2) {
            addCriterion("UPDATETIME between", value1, value2, "UPDATETIME");
            return (Criteria) this;
        }

        public Criteria andUPDATETIMENotBetween(Date value1, Date value2) {
            addCriterion("UPDATETIME not between", value1, value2, "UPDATETIME");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tuser
     *
     * @mbggenerated do_not_delete_during_merge Tue May 14 16:04:15 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}