package com.wildwolf.model;

import java.util.Date;

import com.wildwolf.helper.page.Page;

public class Userlog extends Page{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERLOG.ID
     *
     * @mbggenerated Thu Jan 24 13:11:20 CST 2013
     */
    private String ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERLOG.USERNAME
     *
     * @mbggenerated Thu Jan 24 13:11:20 CST 2013
     */
    private String USERNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERLOG.OPERATION
     *
     * @mbggenerated Thu Jan 24 13:11:20 CST 2013
     */
    private String OPERATION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERLOG.OPERATIONTIME
     *
     * @mbggenerated Thu Jan 24 13:11:20 CST 2013
     */
    private Date OPERATIONTIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERLOG.CREATETIME
     *
     * @mbggenerated Thu Jan 24 13:11:20 CST 2013
     */
    private Date CREATETIME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERLOG.ID
     *
     * @return the value of USERLOG.ID
     *
     * @mbggenerated Thu Jan 24 13:11:20 CST 2013
     */
    public String getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERLOG.ID
     *
     * @param ID the value for USERLOG.ID
     *
     * @mbggenerated Thu Jan 24 13:11:20 CST 2013
     */
    public void setID(String ID) {
        this.ID = ID == null ? null : ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERLOG.USERNAME
     *
     * @return the value of USERLOG.USERNAME
     *
     * @mbggenerated Thu Jan 24 13:11:20 CST 2013
     */
    public String getUSERNAME() {
        return USERNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERLOG.USERNAME
     *
     * @param USERNAME the value for USERLOG.USERNAME
     *
     * @mbggenerated Thu Jan 24 13:11:20 CST 2013
     */
    public void setUSERNAME(String USERNAME) {
        this.USERNAME = USERNAME == null ? null : USERNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERLOG.OPERATION
     *
     * @return the value of USERLOG.OPERATION
     *
     * @mbggenerated Thu Jan 24 13:11:20 CST 2013
     */
    public String getOPERATION() {
        return OPERATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERLOG.OPERATION
     *
     * @param OPERATION the value for USERLOG.OPERATION
     *
     * @mbggenerated Thu Jan 24 13:11:20 CST 2013
     */
    public void setOPERATION(String OPERATION) {
        this.OPERATION = OPERATION == null ? null : OPERATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERLOG.OPERATIONTIME
     *
     * @return the value of USERLOG.OPERATIONTIME
     *
     * @mbggenerated Thu Jan 24 13:11:20 CST 2013
     */
    public Date getOPERATIONTIME() {
        return OPERATIONTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERLOG.OPERATIONTIME
     *
     * @param OPERATIONTIME the value for USERLOG.OPERATIONTIME
     *
     * @mbggenerated Thu Jan 24 13:11:20 CST 2013
     */
    public void setOPERATIONTIME(Date OPERATIONTIME) {
        this.OPERATIONTIME = OPERATIONTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERLOG.CREATETIME
     *
     * @return the value of USERLOG.CREATETIME
     *
     * @mbggenerated Thu Jan 24 13:11:20 CST 2013
     */
    public Date getCREATETIME() {
        return CREATETIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERLOG.CREATETIME
     *
     * @param CREATETIME the value for USERLOG.CREATETIME
     *
     * @mbggenerated Thu Jan 24 13:11:20 CST 2013
     */
    public void setCREATETIME(Date CREATETIME) {
        this.CREATETIME = CREATETIME;
    }
}